"""Explicit source decisions for ordinary Battler branches; no inferred credit."""
from add_review import review,ROOT
import json
existing={(r['file'],r['line']) for r in json.loads((ROOT/'research/semantic-reviews.json').read_text(encoding='utf-8'))}
rows={
478:('Deep Earth doubles weight after native held-item and ability factors, retaining seed weight through a field replacement until switch-out.',['Deep Earth weight modifiers respect native item and ability ordering']),
1104:('Iron Ball grounds outside Deep Earth; Deep Earth cancels its grounding before exceptional levitation.',['Deep Earth grants only the source exceptional levitation list and strips native Levitate under Gravity']),
1110:('Magnet Pull, Contrary, Unaware and Oblivious remain airborne under Deep Earth gravity; ordinary Levitate and source airborne abilities do not.',['Deep Earth grants only the source exceptional levitation list and strips native Levitate under Gravity']),
1131:('Hard Electric field alone disables Comatose sleep traits and status immunity; an Electric overlay does not.',['Electric Terrain disables Comatose trait and status immunity']),
1184:('Deep Earth removes Slow Start Speed and physical Attack penalties while its original five-turn clock continues.',['Deep Earth Slow Start cancels only the native physical Attack and Speed penalty','Slow Start original entry text is absent on Deep Earth without losing duration or expiry']),
1187:('Steadfast Speed is multiplied by 1.5 on the hard Electric field or its overlay.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1190:('New World multiplies grounded Speed by .75; airborne users retain ordinary Speed.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1192:('Water Surface and Murkwater multiply grounded non-Water Speed by .75, except Surge Surfer and Swift Swim, which retain their independent source activations.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1194:('Underwater multiplies non-Water Speed by .5 unless Eelevate, Steelworker or Swift Swim applies.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1202:('Working Float Stone multiplies Speed by 1.2 on Deep Earth.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1207:('Deep Earth cancels Iron Ball native .5 Speed factor; its entry stage loss remains independent.',['ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
1293:('Back Alley floors healing after multiplying .67, except an original maximum-HP heal.',['Back Alley preserves full-HP restoration and minimum one HP']),
1698:('Aegislash Stance Change in Chess/Fairy Tale changes Attack and Defense stages on actual form changes, with original Shield/Blade text.',['Stance Change modifies stages on actual form changes in Chess and Fairy Tale']),
1859:('Glitch RKS System retains source unknown typing with ordinary native model fallback and restores on leaving. Custom animation remains unavailable.',['Holy Silvally uses its native Dark form and Glitch retains unknown typing until restored']),
1860:('Holy RKS System uses native Dark form and original false-god message; custom animation is unavailable.',['Holy Silvally uses its native Dark form and Glitch retains unknown typing until restored']),
2304:('Frozen Dimension changes ordinary Morpeko to Hangry only when needed and prevents the residual Hunger Switch toggle.',['Frozen Dimension forces Morpeko Hangry on entry and stops every end-turn toggle']),
3014:('Comatose original drowsing text is emitted except on the hard Electric field.',['Comatose source entry flavor is suppressed only on the hard Electric field']),
3042:('Infernal disables all Pastel Veil poisoning-prevention and cure callbacks, including updates and partner entries.',['Infernal Pastel Veil allows poison and does not cure it on update']),
3288:('Slow Start original entry text is suppressed on Deep Earth while its five-turn state persists and expires normally.',['Slow Start original entry text is absent on Deep Earth without losing duration or expiry']),
3294:('City Frisk lowers each live opposing Special Defense once with the source Intimidate-like substitute category. Anti-Intimidate abilities only block actual Intimidate, not Frisk; ordinary Clear Body/White Smoke still apply.',['City Frisk special defense loss uses the source Intimidate immunity category']),
3315:('Back Alley Frisk identifies then steals a removable foe item only while the user is empty-handed; Sticky Hold and Substitute retain their native guards.',['City Frisk lowers opposing special defense and Back Alley steals removable items']),
3419:('Quark Drive activates from Electric hard field/overlay, picks the highest staged stat, and reserves Booster Energy until environmental expiry; New World activation is checked by the source global handler.',['paradox environmental boosts activate from hard fields and New World without consuming Booster Energy','field and overlay changes reconcile environmental boosts, preserve clocks and respect Transform','environmental boost expiry consumes Booster Energy once and keeps its replacement boost']),
3545:('King\'s Rock/Razor Fang flinch is exactly 20 percent on Rainbow hard/overlay or Serene Grace, not multiplicatively stacked. Existing flinch moves and Sheer Force with a secondary are excluded; native Substitute/Shield Dust/Covert Cloak remain authoritative.',['Kings Rock and Razor Fang use exactly 20 percent on Rainbow, overlay, or Serene Grace','item flinch preserves inherent flinches and is suppressed by Sheer Force with positive effects']),
4184:('Misty/Rainbow/Starlight Seed creates a two-turn Wish only in an empty slot, using floor((maxHP+1)*.75).',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4192:('Burning/Desert/Volcanic Seeds bind for four turns using the defined native trapping move.',['binding seeds store native move identity and four-turn duration','every defined field Seed activates and is consumed']),
4195:('Swamp Seed changes an eligible ability to Clear Body.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4197:('Corrosive Mist/Murkwater/Corrupted Seeds inflict Toxic with ordinary poison immunity.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4199:('Icy Seed applies the native Spikes layer fraction only while grounded and without Magic Guard.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4204:('Rocky/Cave Seed applies quarter-maxHP Rock effectiveness damage unless Magic Guard; the item is consumed even if that damage is lethal.',['source seed special effects retain Wish rounding, statuses, guards, type and field state','Cave and Rocky Seeds consume even after lethal weakness damage and scale type resistance']),
4214:('Wasteland Seed lays Stealth Rock on both sides and dispatches the original floating-stones line.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4218:('Underwater Seed changes eligible user typing to Water.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4220:('Glitch Seed gives eligible users unknown typing and explicitly applies the source Multitype Arceus exception using native-model type semantics.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4233:('New World Seed imposes native recharge on the next chosen move.',['New World seed applies native recharge instead of an unused volatile']),
4235:('Rejuvenation Inverse Seed changes eligible typing to Normal and ability to Normalize.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4242:('Psychic Seed uses native confusion and immunity handling.',['every defined field Seed activates and is consumed']),
4244:('Dimensional Seed toggles Trick Room with a random 3-8 turn duration.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4254:('Haunted Seed burns subject to ordinary burn immunity.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4256:('Infernal Seed traps the user in its own active slot.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4258:('Deep Earth Seed adds one base weight before field doubling; the weight marker persists until switch-out.',['Deep Earth weight modifiers respect native item and ability ordering']),
4266:('Deux Finalis Seed creates the native four-turn Perish Song clock except Soundproof.',['source seed special effects retain Wish rounding, statuses, guards, type and field state']),
4318:('Electric hard field activates and consumes Cell Battery to raise Attack by one when eligible.',['item switch-in consumption']),
4356:('Deep Earth Iron Ball lowers Speed by two on entry and Magnet lowers Speed/raises Special Attack, independently of item Speed scaling.',['item switch-in consumption','ordinary field speed predicates cover grounding, Water types, abilities, overlays and held items']),
4389:('Corrupted Black Sludge deals quarter maxHP to non-Poison holders, retaining Magic Guard and the source user/partner healing eligibility guard.',['Corrupted Black Sludge doubles healing and damage while retaining source HP and immunity guards']),
4448:('Corrupted Black Sludge heals Poison holders by an eighth maxHP using native healing guards and item suppression.',['Corrupted Black Sludge doubles healing and damage while retaining source HP and immunity guards']),
4979:('Psychic hard field/overlay makes Expanding Force spread even when airborne; its separate native 1.5 power multiplier still requires grounding.',['Expanding Force spreads while airborne on hard Psychic Terrain and an overlay without the grounded power bonus']),
4989:('Deep Earth Gravity becomes a Physical spread attack with half current-HP fixed damage rather than setting Gravity.',['Deep Earth Gravity and Magnet Rise use contextual move behavior']),
5255:('Psychic hard/overlay blocks opposing positive-priority moves against grounded targets, except the Chess King.',['Chess King bypasses Psychic overlays while every other Chess piece remains blocked']),
5259:('Chess King priority bypasses a Psychic overlay for every King move; other pieces remain blocked.',['Chess King bypasses Psychic overlays while every other Chess piece remains blocked']),
5410:('Prankster status moves reach Dark foes on Bewitched and Glitch but keep native Dark immunity elsewhere.',['Prankster status moves reach Dark foes only on source exception fields']),
5558:('Short Circuit Lightning Rod consumes one field cycle roll for Special Attack stage gains, with Electric overlay maximizing it.',['Factory Motor Drive and Short Circuit cycle use native interception once']),
5572:('Factory Motor Drive raises Speed by two on Electric interception.',['Factory Motor Drive and Short Circuit cycle use native interception once']),
5573:('Short Circuit Motor Drive uses source stage gains [1,2,0,1,3] from the shared cycle.',['Factory Motor Drive and Short Circuit cycle use native interception once']),
5587:('Short Circuit Volt Absorb restores maxHP times its locked cycle multiplier divided by four; an Electric overlay maximizes the roll.',['Short Circuit Volt Absorb scales healing and overlay maximizes the cycle']),
5790:('Deep Earth permits Magnet Rise under Gravity and replaces it with Speed +2 rather than levitation.',['Deep Earth Gravity and Magnet Rise use contextual move behavior']),
5965:('Chess Kowtow Cleave bypasses Armor Tail, Dazzling and Queenly Majesty priority blocks; quarter damage applies only to actual protection states.',['Chess Kowtow Cleave pierces each opposing priority-blocking ability without quartering damage']),
7072:('Dark Aura drains a quarter of inflicted victim damage on Dimensional/Frozen and a third on Deux; source Aura Break, Big Root and Liquid Ooze remain independent.',['Dark Aura drain follows victim damage and Aura Break inverts recipient damage','Dark Aura drain honors Big Root and Liquid Ooze']),
7074:('Deux Dark Aura drain divisor is three, not four.',['Dark Aura drains and Shell Bell doubles on their source fields']),
7268:('Stat-query Slow Start shares the Deep Earth exclusion with the damage calculation.',['Deep Earth Slow Start cancels only the native physical Attack and Speed penalty']),
7269:('Stat-query Hustle uses 1.75 on Back Alley/City instead of 1.5.',['ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate']),
7273:('Orichalcum Pulse draws its native Attack boost from New World without creating sun.',['stat-doubling and terrain abilities follow their source field conditions']),
7275:('New World global ruin factor is .667.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7276:('Holy global ruin factor is .875.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7277:('Deux Finalis allied Tablets of Ruin spares its side; opposing holders retain the ruin effect.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7280:('Pure Power physical Attack is not doubled under Psychic hard field/overlay.',['stat-doubling and terrain abilities follow their source field conditions']),
7300:('Marvel Scale is always active on the specified six fields and also retains status activation.',['Marvel Scale and Grass Pelt are always active on their source fields']),
7302:('Grass Pelt activates on Forest/Grassy hard field or Grassy overlay.',['Marvel Scale and Grass Pelt are always active on their source fields']),
7310:('New World defensive ruin multiplier is .667.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7311:('Holy defensive ruin multiplier is .875.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7330:('New World Vessel of Ruin Special Attack factor is .667.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7331:('Holy Vessel of Ruin Special Attack factor is .875.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7337:('Psychic Pure Power doubles Special Attack instead of physical Attack, including overlays.',['stat-doubling and terrain abilities follow their source field conditions']),
7339:('Plus/Minus activates independently from a partner on Short Circuit/Electric hard or Electric overlay.',['stat-doubling and terrain abilities follow their source field conditions']),
7344:('Frozen Dimension disables ordinary Solar Power Special Attack even in sun; other fields retain Utility Umbrella gating. The Castform Crest clause is excluded.',['stat-doubling and terrain abilities follow their source field conditions']),
7345:('Hadron Engine draws its native Special Attack boost from New World/Electric hard field/overlay.',['stat-doubling and terrain abilities follow their source field conditions']),
7352:('Deux Finalis allied Vessel of Ruin spares its side.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7385:('New World Beads of Ruin Special Defense factor is .667.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7386:('Holy Beads of Ruin Special Defense factor is .875.',['ruin abilities use the New World and Holy factors and spare a partner on the source dimensional list']),
7502:('Colosseum chosen switches resolve at the user normal priority-zero Speed slot; forced replacements and pivot requests retain immediate switching.',['Colosseum voluntary switches act at priority zero in Speed order','Colosseum switch timing respects negative priority and leaves forced replacements immediate'])
}
for line,(semantics,tests) in rows.items():
 review('Battler.rb',line,'implemented_and_tested',semantics,tests,replace=('Battler.rb',line) in existing,exclusions=['Castform Crest sunny form'] if line==7344 else [])
for line in [1392,3471]:review('Battler.rb',line,'excluded_crest','The enclosing Raikou Crest flag ends its own generated Electric field/overlay on faint or leaving; Crests are explicitly excluded.',exclusions=['Raikou Crest'],replace=('Battler.rb',line) in existing)
for line in [531,564]:review('Battle.rb',line,'implemented_and_tested','Source environmental paradox activation/expiry, highest staged stat, Transform guard, native item boost retention and exact original messages are implemented by the generic environmental ability reconciler.',[
 'paradox environmental boosts activate from hard fields and New World without consuming Booster Energy','environmental boost expiry consumes Booster Energy once and keeps its replacement boost','field and overlay changes reconcile environmental boosts, preserve clocks and respect Transform','paradox weather suppression and Booster Energy modes stay independent of qualifying fields'],replace=('Battle.rb',line) in existing)
print('Recorded',len(rows)+4,'explicit Battler/environment source decisions')
