"""Explicit source decisions from the distributed damage/type completion pass.

This script only records the named spans and focused regression receipts; it
never infers coverage from matching field IDs, generated rows or test totals.
"""
from add_review import review
import json
from pathlib import Path
existing={(r['file'],r['line']) for r in json.loads((Path(__file__).parent/'semantic-reviews.json').read_text(encoding='utf8'))}
rows={
605:('Glitch Genesect Shock Drive intercepts Electric attacks, retains the Drive and raises Speed once.', ['Glitch Genesect Drives absorb corresponding types and retain their item']),
626:('Desert sun lets Water/Grass defenders absorb all Water attacking types for a quarter heal; Utility Umbrella and self/ally targeting guards remain.', ['sunny Desert Water absorption and Magma Armor obey field conditions','Glitch Drive and sunny Desert absorptions emit the original full-HP and repeat messages']),
627:('Glitch Genesect Douse Drive intercepts Water and heals one quarter with full-HP failure text.', ['Glitch Genesect Drives absorb corresponding types and retain their item','Glitch Drive and sunny Desert absorptions emit the original full-HP and repeat messages']),
632:('Glitch Genesect Chill Drive intercepts Ice and heals one quarter with full-HP failure text.', ['Glitch Genesect Drives absorb corresponding types and retain their item','Glitch Drive and sunny Desert absorptions emit the original full-HP and repeat messages']),
649:('Frozen Dimension skips Fire absorption, retaining the stored Flash Fire state for later restoration. Other fields keep native interception and Glitch Burn Drive.', ['Frozen Dimension disables Flash Fire and restores it on replacement','Frozen Dimension suppresses stored Flash Fire power and restores it after replacement','Glitch Genesect Drives absorb corresponding types and retain their item']),
654:('Glitch Genesect Burn Drive stores the Flash Fire boost, retains the item, and replaces repeat-activation flavor with the original ineffective message.', ['Glitch Drive and sunny Desert absorptions emit the original full-HP and repeat messages']),
672:('Volcanic Top, Dragon Den and Infernal Magma Armor block every Fire attacking type unless suppressed; Infernal Wildfire primary Fire bypasses the interception.', ['Infernal Wildfire bypasses Magma Armor while other fields and suppressed Wildfire retain immunity','sunny Desert Water absorption and Magma Armor obey field conditions']),
720:('Deep Earth selects Unaware/Oblivious/Magnet Pull/Contrary/Gravity Control as exceptional airborne abilities instead of the ordinary Levitate family; roots ground them.', ['Deep Earth grants only the source exceptional levitation list and strips native Levitate under Gravity']),
779:('Sky added Flying effectiveness intentionally tests the first defender type twice and ignores resistances. The primary attack still uses its ordinary chart.', ['Sky added Flying type preserves the source first-type-twice behavior']),
797:('Special Normal attacks receive a sampled extra type on Rainbow, locked per move and separate from overlay rolls.', ['secondary types activate absorbing abilities once','Rainbow overlay adds an independent random attacking type and locks it across hits']),
801:('Special Flying attacks on Corrosive Mist also attack as Poison; physical Flying attacks keep their original attacking types.', ['source field move types and Glitch categories follow the shipped Rejuvenation switches']),
805:('Short Circuit Steelworker Steel attacks receive Electric as an additional attacking type.', ['source field move types and Glitch categories follow the shipped Rejuvenation switches']),
809:('Crystal Rock attacks and its specified ordinary moves cycle Fire/Water/Grass/Psychic once per move; hard-field cycle and Rainbow overlay roll are independent.', ['crystal secondary type rolls sequentially','Rainbow overlay adds an independent random attacking type and locks it across hits']),
837:('Rainbow overlays add a separate sampled type to special Normal attacks, without overwriting a hard field type or consuming its sequential roll.', ['Rainbow overlay adds an independent random attacking type and locks it across hits']),
980:('Merciless guarantees crits on Corrosive Mist regardless of flight and on Corrosive/Wasteland/Murkwater for grounded users; native poisoning and crit prevention remain.', ['Merciless and Colosseum guaranteed crit rules keep grounding and Battle Armor restrictions']),
981:('Colosseum targets with Rattled/Wimp Out are critically hit unless the ordinary CriticalHit event prevents it.', ['Merciless and Colosseum guaranteed crit rules keep grounding and Battle Armor restrictions']),
1008:('Glitch adds a crit stage using stored Speed, ignoring Speed stages.', ['Glitch critical stage compares stored speed, not boosted speed']),
1009:('Chess adds stages for Reckless/Gorilla Tactics targets, their last rampage/Tantrum, and Merciless below 80% HP. The source 60%/40% branches are unreachable and are not repaired.', ['Chess critical modifiers preserve the unreachable lower HP branch']),
1185:('Chess Kowtow Cleave deals quarter damage through individual protection and qualifying Mat Block/Wide Guard/Quick Guard, skipping shield contact consequences and dispatching source text once.', ['Chess Kowtow Cleave partially pierces Protect with quarter damage and source flavor','all Chess shields are partially pierced while their native contact penalties do not trigger']),
1271:('Duskilate is registered: ordinary Normal moves become Dark and gain 1.2 power outside Glitch. Rejuv disables the conversion and the boost on Glitch; the inactive Reborn clause is not applied.', ['Duskilate registers ordinary conversion and preserves Glitch Normal typing without a boost']),
1285:('Deux Finalis Beads of Ruin adds 1.3 base power only against Petrification, independently of its native defensive ruin effect.', ['Ruin abilities add source Petrification multipliers on the correct stat branch']),
1391:('Chess move-sensitive target ability/confusion factors, Queen-or-Majesty single factor and Knight-versus-Queen factor are applied at base power with source flavor.', ['Chess move-sensitive base-power factors apply only once per source guard','Chess knight versus queen triples base power and ordinary queens dominate without stacking Majesty']),
1406:('Big Top striker uses source 0..13 RNG, ability maximization, Attack-stage adjustment and 0..14 clamp; previews average the roll list; Casual/Frenzy scales the result.', ['Big Top striker clamps its randomized stat-stage roll and averages source preview rolls','dynamic field multipliers preserve Casual, Field Frenzy and online behavior with source roll messages']),
1413:('Short Circuit cycles its five power factors once per move, locks across hits, and maximizes under Electric overlay; source difficulty scaling and exact roll messages remain.', ['short circuit power roll locks across multiple hits','Short Circuit Volt Absorb scales healing and overlay maximizes the cycle','dynamic field multipliers preserve Casual, Field Frenzy and online behavior with source roll messages']),
1420:('Mountain/Snowy Mountain/Volcanic Top strong winds boost wind moves or special Flying attacks by a difficulty-scaled 1.5 at base power.', ['Mountain wind amplification and Deep Earth priority messages apply at base power']),
1434:('Deep Earth positive and negative priorities apply difficulty-scaled 0.7/1.3 factors with separate source messages.', ['dynamic field multipliers preserve Casual, Field Frenzy and online behavior with source roll messages']),
1513:('Deep Earth cancels native Slow Start physical Attack and Speed penalties without boosting Special Attack.', ['Deep Earth Slow Start cancels only the native physical Attack and Speed penalty']),
1528:('Underwater halves physical attack unless the user is Water, an attacking type is Water, or its ability is Eelevate/Steelworker/Swift Swim; Special Attack is unchanged.', ['Underwater physical attack reduction respects Water users, attacking types and each source ability']),
1570:('A working defender Never-Melt Ice applies 0.66 at the Fire attack-stat stage on Frozen Dimension or the battle cold flag, once; item suppression and original named-move feedback are honored.', ['Never-Melt Ice reduces the Fire attack stat once and emits the original item feedback']),
1592:('The enclosing non-Indoor block applies Victory Star and Propeller Tail bonuses, Chess ordinary offense factors and the listed field offense abilities. Skill Link ordinary variable multi-hit behavior is retained; the Cinccino Crest clause is excluded.', ['Victory Star, Propeller Tail and Skill Link gain their source field attack bonuses','Chess offense stacks ordinary ability and active Illusion factors and preserves Competitive HP branch','ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate']),
1601:('Chess applies Reckless/Gorilla Tactics and active Illusion independently at attack-stat stage, plus Competitive HP interpolation and the source below-20% override.', ['Chess offense stacks ordinary ability and active Illusion factors and preserves Competitive HP branch','Chess Illusion multiplier depends on an active disguise, surviving ability replacement']),
1615:('Fairy Tale Queenly Majesty boosts both offensive stat categories by 1.5; Chess uses its separate base-power Queen-or-ability rule.', ['ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate','Chess queen boost does not double Queenly Majesty']),
1616:('Long Reach boosts offensive stats on Mountain/Snowy Mountain/Volcanic Top/Sky by 1.5.', ['ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate']),
1617:('Corrosion boosts offensive stats on Corrosive/Corrosive Mist/Corrupted by 1.5.', ['ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate']),
1619:('Holy Purifying Salt boosts offensive stats by 1.5, alongside the independent native Ghost protection.', ['ordinary field offense abilities act at the Attack or Special Attack stage without a final-damage duplicate']),
1692:('When Glitch borrows defensive Special Attack, ordinary Solar Power sunlight and Utility Umbrella modifiers participate in selecting and applying the stat. Castform Crest is excluded.', ['Glitch defensive shared Special borrows the fully modified Special Attack under ordinary field overlays']),
1694:('Defensive Special Attack borrowing on Glitch includes Pure Power under a Psychic overlay.', ['Glitch defensive shared Special borrows the fully modified Special Attack under ordinary field overlays']),
1696:('Defensive Special Attack borrowing includes ordinary Plus/Minus partners and Electric overlays. Plusle/Minun Crest clauses are excluded.', ['Glitch defensive shared Special borrows the fully modified Special Attack under ordinary field overlays','stat-doubling and terrain abilities follow their source field conditions']),
1701:('Defensive Special Attack borrowing includes ordinary Hadron Engine under Electric overlays. The shared pool is active only on Glitch; direct stat ability branches are tested separately on their hard fields.', ['Glitch defensive shared Special borrows the fully modified Special Attack under ordinary field overlays','stat-doubling and terrain abilities follow their source field conditions']),
1749:('Glitch Explosion/Self-Destruct halve physical Defense before damage calculation.', ['Glitch Explosion and Self-Destruct halve physical defense only on that field']),
2126:('Chess Pawn full-HP damage survival occurs once per active battler slot and not after its save has been consumed. Ordinary native survival effects remain; Rampardos Crest is excluded.', ['Chess Pawn survival is limited to one full-HP save per active slot and checks actual damage','Chess allocates pieces with source party order and king preference']),
2143:('Colosseum Stalwart survives full-HP lethal damage with one HP unless ability suppression applies; the ordinary OHKO immunity is separately tested.', ['Colosseum Stalwart saves full-HP lethal damage with source text unless Mold Breaker suppresses it']),
2215:('Concert 1..3 grows one stage after the critical-hit message and before HP loss, so the current damage uses the previous field; stage 4 is stable.', ['Concert critical-hit progression follows the crit message and changes only subsequent damage']),
2321:('Deep Earth Gravity is an ordinary level-based fixed damage attack, retaining its environmental Gravity reactions.', ['Deep Earth Gravity and Magnet Rise use contextual move behavior']),
2327:('Haunted Ominous Wind replaces its secondary chance with 20 before the native random roll.', ['ordinary field secondary-effect chance overrides execute before the native random roll']),
2332:('Fairy Tale Strange Steam guarantees its confusion secondary, subject to native secondary protection.', ['ordinary field secondary-effect chance overrides execute before the native random roll']),
2333:('Haunted Lick guarantees its paralysis secondary, subject to native secondary protection.', ['ordinary field secondary-effect chance overrides execute before the native random roll']),
2334:('Wasteland Dire Claw guarantees its source random status secondary.', ['ordinary field secondary-effect chance overrides execute before the native random roll']),
2335:('Infernal Infernal Parade guarantees its burn secondary.', ['ordinary field secondary-effect chance overrides execute before the native random roll']),
2336:('Deux Finalis Freezing Glare guarantees the field Petrification secondary, retaining native immunity and suppression checks.', ['ordinary field secondary-effect chance overrides execute before the native random roll','ordinary field moves inflict Petrification with native secondary gating']),
2337:('Deux Finalis Bitter Blade guarantees the field Petrification secondary.', ['ordinary field secondary-effect chance overrides execute before the native random roll','ordinary field moves inflict Petrification with native secondary gating']),
}
# Only these embedded clauses are excluded; all ordinary behavior of the spans is tested.
exclusions={1592:['Cinccino Crest variable multi-hit contribution at 1618'],1692:['Castform Crest sunny form'],1696:['Plusle/Minun Crest partner exceptions'],2126:['Rampardos Crest survival block at 2139-2141']}
for line,(semantics,tests) in rows.items():
    review('Battle_Move.rb',line,'implemented_and_tested',semantics,tests,exclusions=exclusions.get(line,[]),replace=('Battle_Move.rb',line) in existing)
print('Recorded',len(rows),'explicit distributed move/type/damage reviews')
