"""Synchronized validation for declarative environmental ability activation."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
p=ROOT/'mod/src/main/resources/rejuvenation-engine.js';s=p.read_text(encoding='utf-8')
at=s.index('      for(const [iid,callbacks]of Object.entries(f.itemHandlers')
s=s[:at]+"      for(const [aid,row]of Object.entries(f.environmentAbilities || {})){if(!['quarkdrive','protosynthesis'].includes(aid) || Object.keys(row).sort().join()!=='boosterMessage,callback,condition,expiryMessage,messages,source' || !['onTerrainChange','onWeatherChange'].includes(row.callback) || typeof row.expiryMessage!=='string' || typeof row.boosterMessage!=='string' || typeof row.source!=='string' || !Array.isArray(row.messages) || !row.messages.length)throw new Error('Invalid environmental ability');checkCondition(row.condition);for(const r of row.messages){if(Object.keys(r).sort().join()!=='condition,text' || typeof r.text!=='string')throw new Error('Invalid environmental ability message');checkCondition(r.condition);}}\n"+s[at:];p.write_text(s,encoding='utf-8')
p=ROOT/'research/validate.py';s=p.read_text(encoding='utf-8');at=s.index("    for iid,callbacks in f.get('itemHandlers'")
s=s[:at]+"    for aid,row in f.get('environmentAbilities',{}).items():\n        reference('abilities',aid,name);ensure(aid in ['quarkdrive','protosynthesis'] and set(row)=={'boosterMessage','callback','condition','expiryMessage','messages','source'} and row['callback'] in ['onTerrainChange','onWeatherChange'] and all(isinstance(row[k],str) for k in ['expiryMessage','boosterMessage','source']) and isinstance(row['messages'],list) and len(row['messages'])>0,name,'invalid environmental ability');check_condition(row['condition'],name)\n        for r in row['messages']:ensure(set(r)=={'condition','text'} and isinstance(r['text'],str),name,'invalid environmental message');check_condition(r['condition'],name)\n"+s[at:];p.write_text(s,encoding='utf-8')
p=ROOT/'mod/src/main/java/dev/rejuvenation/CatalogValidator.java';s=p.read_text(encoding='utf-8');at=s.index('   if(fieldExtra.has("itemHandlers"))')
s=s[:at]+'''   if(fieldExtra.has("environmentAbilities"))for(var ability:fieldExtra.getAsJsonObject("environmentAbilities").entrySet()){var row=ability.getValue().getAsJsonObject();require(words("quarkdrive protosynthesis").contains(ability.getKey()) && row.keySet().equals(words("boosterMessage callback condition expiryMessage messages source")) && words("onTerrainChange onWeatherChange").contains(row.get("callback").getAsString()),entry.getKey(),"Invalid environmental ability");condition(row.get("condition"),fields,entry.getKey());for(String key:List.of("boosterMessage","expiryMessage","source"))require(row.get(key).isJsonPrimitive() && row.getAsJsonPrimitive(key).isString(),entry.getKey(),"Invalid environmental text");require(row.get("messages").isJsonArray() && !row.getAsJsonArray("messages").isEmpty(),entry.getKey(),"Empty environmental messages");for(var message:row.getAsJsonArray("messages")){var r=message.getAsJsonObject();require(r.keySet().equals(words("condition text")) && r.get("text").isJsonPrimitive() && r.getAsJsonPrimitive("text").isString(),entry.getKey(),"Invalid environmental message");condition(r.get("condition"),fields,entry.getKey());}}
'''+s[at:];p.write_text(s,encoding='utf-8')
