package dev.rejuvenation;

import com.google.gson.*;
import com.google.gson.stream.*;
import java.io.*;
import java.util.*;
import java.util.stream.StreamSupport;

/** Shared reload boundary. No scripts, expressions, reflection or arbitrary paths. */
public final class CatalogValidator {
 private CatalogValidator() {}
 private static final Set<String> CONDITIONS=words("always all any not move sourceMove moveType category flag field backup grounded ability item type species form formName status weather weatherFor incomingWeather startedCondition damageSource counter hp priority foe missed volatile value semiInvulnerable globalAbility effectiveness turnsActive stateFlag overlay weatherActive pokemonStatus targetStatus chance samePokemon statsLowered selfInflicted contact hasAlly level transformed wild itemStealable usableMove pokemonActive pokemonFlag statSumComparison sideAbility sideCondition role moveTarget fullHealing faster lastMove attackType foeFainted effectiveAbility pseudoWeather abilityChangedType basePower holderAllied hitEffectiveness allyAbility variableMultihit holderIsUser sideItem holderAbilityState baseMoveType actorType boostStage connected effectId calledBy accuracyMiss damageDealt drainHealed canFlinch baseCanFlinch sheerForce allyCanHeal oneHitKO zMove immunityType volatileSourceMove canHeal");
 private static final Set<String> ACTIONS=words("multiply add set cap reject message boost heal damage status ability type moveType volatile consume form forcedType itemForm randomType randomForm forEach abilityMessage addSecondary stealItem preventStatLoss secondaryChance pseudoWeather progress changeField destroyField oldCategory inverse ice_spikes accuracy_cloud arm_eruption cave_collapse mist_explosion water_pollution hazardBurst restoreTypes trap setHPFraction harvestBerry volatileDuration clearHazards bothHazards sideCondition typedDamage spikeDamage wish trickRoom perishSong removeVolatile cureStatus randomBoost randomStat randomStatus conditional transferStat castling counter setFlag setPokemonFlag bindFieldClock weatherTemporary hpPower cyclePower randomPower extraType residualDamage flashFire concertNoise moveMessage groupMessage clearWeather setWeather clearOverlay moveProperty adjustWish mimicry survive moveBehavior criticalStage weightDelta removeCallbacks pairField createField baseAccuracy clearBoosts identifyItems boostByHighestStat streakPower healByDamage damageShare fieldMove randomWeather reconcileWeather accuracyPenalty mechanic");
 private static final Set<String> EVENTS=words("activate fieldResidual residual switchIn pokemonEntry basePower modifyMove afterMove accuracy priority damage attack specialAttack defense specialDefense speed tryHeal setStatus tryHit weatherChange effectiveness receivedDamage tryVolatile criticalRatio weight chargeMove tryMove overlayIn formChange setWeather afterHit pseudoWeatherStart perfectAccuracy baseAccuracy criticalHit tryFlinch flinch snatch afterFaint weatherReconcile criticalMessage modifyMoveLate sideConditionStart fractionalPriority trapPokemon finalAccuracy");
 private static final Set<String> PATHS=words("boosts self.boosts secondaries.0.self.boosts secondaries.0.self secondaries.0.boosts heal recoil basePower damage priority accuracy target spreadModifier sideCondition category status zMove.boost secondaries secondaries.0.status pseudoWeather flags.gravity flags.protect flags.sound flags.bypasssub selfBoost self pranksterBoosted forceSwitch maxHPRecoil magnitude drain ignoreImmunity overrideOffensiveStat overrideDefensiveStat");
 private static Set<String> words(String s) { return Set.of(s.split(" ")); }
 private static void require(boolean test,String where,String detail){if(!test)throw new IllegalArgumentException(where+": "+detail);}
 private static boolean numeric(JsonElement e){return e!=null && e.isJsonPrimitive() && e.getAsJsonPrimitive().isNumber() && Double.isFinite(e.getAsDouble());}
 private static boolean integer(JsonElement e,int min,int max){return numeric(e) && e.getAsDouble()==e.getAsInt() && e.getAsInt()>=min && e.getAsInt()<=max;}
 private static void probability(JsonObject a,String where){require(integer(a.get("numerator"),0,10000) && integer(a.get("denominator"),1,10000) && a.get("numerator").getAsInt()<=a.get("denominator").getAsInt(),where,"Invalid probability");}
 private static void stats(JsonObject a,String where){require(a!=null && !a.isEmpty(),where,"Missing stat map");for(var r:a.entrySet())require(words("atk def spa spd spe accuracy evasion").contains(r.getKey()) && integer(r.getValue(),-12,12) && r.getValue().getAsInt()!=0,where,"Invalid stat map");}
 private static void statusPool(JsonObject a,JsonObject fields,String where){var values=a.getAsJsonArray("values");require(values!=null && !values.isEmpty(),where,"Missing status pool");for(var v:values)require(words("brn frz par psn tox slp ptr").contains(v.getAsString()),where,"Invalid pooled status");if(a.has("force")){var force=a.getAsJsonObject("force");condition(force.get("condition"),fields,where);require(values.contains(force.get("status")),where,"Invalid forced status");}}
 public static JsonObject read(InputStream stream) throws IOException {
  try(var reader=new JsonReader(new InputStreamReader(stream,java.nio.charset.StandardCharsets.UTF_8))){
   reader.setLenient(false);var result=tree(reader);require(reader.peek()==JsonToken.END_DOCUMENT,"JSON","Trailing content");return result.getAsJsonObject();
  }
 }
 private static JsonElement tree(JsonReader r) throws IOException {
  return switch(r.peek()){
   case BEGIN_OBJECT -> {var o=new JsonObject();r.beginObject();while(r.hasNext()){String key=r.nextName();require(!o.has(key),r.getPath(),"Duplicate property "+key);o.add(key,tree(r));}r.endObject();yield o;}
   case BEGIN_ARRAY -> {var a=new JsonArray();r.beginArray();while(r.hasNext())a.add(tree(r));r.endArray();yield a;}
   case STRING -> new JsonPrimitive(r.nextString());
   case NUMBER -> {String v=r.nextString();yield new JsonPrimitive(new java.math.BigDecimal(v));}
   case BOOLEAN -> new JsonPrimitive(r.nextBoolean());
   case NULL -> {r.nextNull();yield JsonNull.INSTANCE;}
   default -> throw new IllegalArgumentException(r.getPath()+": Invalid JSON token");
  };
 }
 public static void validate(JsonObject catalog){
  JsonObject fields=catalog.getAsJsonObject("fields");require(fields!=null && fields.has("rejuvenation:indoor"),"catalog","Missing fallback field");
  if(catalog.has("trainers")){
   require(catalog.get("trainers").isJsonObject(),"trainers","Invalid trainer field map");
   for(var trainer:catalog.getAsJsonObject("trainers").entrySet()){
    String where="trainer/"+trainer.getKey();require(trainer.getKey().matches("[a-z0-9_.-]+") && trainer.getValue().isJsonObject(),where,"Invalid trainer ID");
    var row=trainer.getValue().getAsJsonObject();
    require(words("field winShare indoorWinShare").containsAll(row.keySet()) && row.has("field") && row.get("field").isJsonPrimitive()
     && fields.has(row.get("field").getAsString()) && !row.get("field").getAsString().equals("rejuvenation:indoor"),where,"Invalid trainer field");
    for(String key:words("winShare indoorWinShare"))if(row.has(key))require(row.get(key).isJsonPrimitive() && row.get(key).getAsJsonPrimitive().isNumber()
     && row.get(key).getAsDouble()>=0 && row.get(key).getAsDouble()<=1,where,"Invalid trainer score");
   }
  }
  JsonObject declared=catalog.has("abilities")?catalog.getAsJsonObject("abilities"):new JsonObject();
  for(var ability:declared.entrySet()){
   String where="ability/"+ability.getKey();require(ability.getKey().matches("[a-z0-9]+") && ability.getValue().isJsonObject(),where,"Invalid declared ability ID");
   var row=ability.getValue().getAsJsonObject();
   require(words("name num description flags inherit callbacks soundMoveTypes airborne airborneBeforeGravity").containsAll(row.keySet()) && row.keySet().containsAll(words("name description flags callbacks")),where,"Invalid declared ability keys");
   for(String key:List.of("name","description"))require(row.get(key).isJsonPrimitive() && row.getAsJsonPrimitive(key).isString() && !row.get(key).getAsString().isEmpty(),where,"Invalid ability metadata");
   require((!row.has("num") || integer(row.get("num"),1,10000)) && row.get("flags").isJsonObject() && row.get("callbacks").isJsonObject(),where,"Invalid ability metadata");
   for(var flag:row.getAsJsonObject("flags").entrySet())require(words("breakable cantsuppress notrace noreceiver noentrain noskillSwap failroleplay").contains(flag.getKey()) && integer(flag.getValue(),1,1),where,"Invalid ability flag");
   if(row.has("inherit"))require(row.get("inherit").isJsonPrimitive() && row.get("inherit").getAsString().matches("[a-z0-9]+") && !declared.has(row.get("inherit").getAsString()),where,"Invalid ability inheritance");
   if(row.has("airborneBeforeGravity"))require(row.get("airborneBeforeGravity").isJsonPrimitive() && row.getAsJsonPrimitive("airborneBeforeGravity").isBoolean() && row.has("airborne") && row.getAsJsonPrimitive("airborne").isBoolean() && row.get("airborne").getAsBoolean(),where,"Invalid gravity-independent ability");
   if(row.has("airborne"))require(row.get("airborne").isJsonPrimitive() && row.getAsJsonPrimitive("airborne").isBoolean(),where,"Invalid airborne ability");
   if(row.has("soundMoveTypes")){require(row.get("soundMoveTypes").isJsonArray() && !row.getAsJsonArray("soundMoveTypes").isEmpty(),where,"Invalid sound move types");for(var t:row.getAsJsonArray("soundMoveTypes"))require(t.isJsonPrimitive() && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy").contains(t.getAsString()),where,"Invalid sound move types");}
   for(var callback:row.getAsJsonObject("callbacks").entrySet()){
    require(words("onStart onModifyMove onBasePower onSourceModifyAccuracy onSourceAccuracy onModifyCritRatio onAllyModifyCritRatio onTryHit onModifyType onModifyAtk onModifySpA onResidual onDamagingHit onImmunity onBeforeResidual onEnd").contains(callback.getKey()) && callback.getValue().isJsonObject(),where,"Invalid declared callback");
    var r=callback.getValue().getAsJsonObject();require(r.keySet().equals(words("actions condition mode source")) && words("replace append prepend scaleBoosts").contains(r.get("mode").getAsString()),where,"Invalid declared callback");
    condition(r.get("condition"),fields,where);actions(r.getAsJsonArray("actions"),fields,where);
   }
  }
  for(var entry:fields.entrySet()){
   var fieldExtra=entry.getValue().getAsJsonObject();
   if(fieldExtra.has("weatherDefinitions"))for(var d:fieldExtra.getAsJsonObject("weatherDefinitions").entrySet()){
    var r=d.getValue().getAsJsonObject();String at=entry.getKey()+"/weather/"+d.getKey();require(d.getKey().matches("[a-z0-9]+") && r.keySet().equals(words("name duration damageFraction damageMessage startMessage endMessage excludedAbilities excludedItems excludedVolatiles excludedFlags source")) && integer(r.get("duration"),1,20) && numeric(r.get("damageFraction")) && r.get("damageFraction").getAsDouble()>0 && r.get("damageFraction").getAsDouble()<=1,at,"Invalid weather definition");
    for(String k:words("name source damageMessage startMessage endMessage"))require(r.get(k).isJsonPrimitive() && r.getAsJsonPrimitive(k).isString(),at,"Invalid weather text");
    for(String k:words("excludedAbilities excludedItems excludedVolatiles excludedFlags")){require(r.get(k).isJsonArray(),at,"Invalid weather exclusions");for(var v:r.getAsJsonArray(k))require(v.isJsonPrimitive() && v.getAsJsonPrimitive().isString() && v.getAsString().matches("[a-z0-9]+"),at,"Invalid weather exclusion");}
   }
   if(fieldExtra.has("extraTypePolicies"))for(var v:fieldExtra.getAsJsonObject("extraTypePolicies").entrySet()){var r=v.getValue().getAsJsonObject();require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow").contains(v.getKey()) && r.keySet().equals(words("mode source")) && r.get("mode").getAsString().equals("firstWeaknessTwice") && r.get("source").isJsonPrimitive() && r.getAsJsonPrimitive("source").isString(),entry.getKey(),"Invalid secondary type policy");}
   if(fieldExtra.has("typeFlagInteractions"))for(var v:fieldExtra.getAsJsonArray("typeFlagInteractions")){
    var r=v.getAsJsonObject();require(r.keySet().equals(words("attackType flag flagged unflagged source")) && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow").contains(r.get("attackType").getAsString()) && r.get("flag").getAsString().matches("[a-z0-9]+") && integer(r.get("flagged"),-1,1) && integer(r.get("unflagged"),-1,1) && r.get("source").isJsonPrimitive() && r.getAsJsonPrimitive("source").isString(),entry.getKey(),"Invalid type flag interaction");
   }
   if(fieldExtra.has("typeDefinitions"))for(var d:fieldExtra.getAsJsonObject("typeDefinitions").entrySet()){
    var r=d.getValue().getAsJsonObject();String at=entry.getKey()+"/type/"+d.getKey();require(d.getKey().equals("Shadow") && r.keySet().equals(words("displayName hue textureBasis damageTaken outgoing flagInteraction source")) && r.get("displayName").isJsonPrimitive() && r.getAsJsonPrimitive("displayName").isString() && r.get("source").isJsonPrimitive() && r.getAsJsonPrimitive("source").isString() && integer(r.get("hue"),0,360) && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy").contains(r.get("textureBasis").getAsString()),at,"Invalid custom type");
    for(String k:words("damageTaken outgoing")){require(r.get(k).isJsonObject(),at,"Invalid custom type chart");for(var v:r.getAsJsonObject(k).entrySet())require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow").contains(v.getKey()) && integer(v.getValue(),0,3),at,"Invalid custom type chart");}
    var flag=r.getAsJsonObject("flagInteraction");require(flag.keySet().equals(words("flag flagged unflagged unflaggedExceptions")) && flag.get("flag").getAsString().matches("[a-z0-9]+") && integer(flag.get("flagged"),-1,1) && integer(flag.get("unflagged"),-1,1) && flag.get("unflaggedExceptions").isJsonArray(),at,"Invalid custom type flag");for(var t:flag.getAsJsonArray("unflaggedExceptions"))require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow").contains(t.getAsString()),at,"Invalid custom type exception");
   }
   if(fieldExtra.has("protectionPolicy"))for(var policy:fieldExtra.getAsJsonObject("protectionPolicy").entrySet()){
    var row=policy.getValue().getAsJsonObject();require(words("kingsshield obstruct silktrap burningbulwark spikyshield banefulbunker protect").contains(policy.getKey()) && words("blockStatus contactBoosts contactFraction source").containsAll(row.keySet()) && row.has("source"),entry.getKey(),"Invalid protection policy");
    if(row.has("blockStatus"))require(row.get("blockStatus").getAsJsonPrimitive().isBoolean() && row.get("blockStatus").getAsBoolean(),entry.getKey(),"Invalid protection status block");
    if(row.has("contactBoosts"))stats(row.getAsJsonObject("contactBoosts"),entry.getKey());
    if(row.has("contactFraction"))require(numeric(row.get("contactFraction")) && row.get("contactFraction").getAsDouble()>0 && row.get("contactFraction").getAsDouble()<=1,entry.getKey(),"Invalid protection contact damage");
   }
   if(fieldExtra.has("switchTiming"))require(fieldExtra.get("switchTiming").isJsonPrimitive() && fieldExtra.get("switchTiming").getAsString().equals("action"),entry.getKey(),"Invalid switch timing");
   if(fieldExtra.has("damageRoll"))require(integer(fieldExtra.get("damageRoll"),85,100),entry.getKey(),"Invalid fixed damage roll");
   if(fieldExtra.has("nativeFormTyping")){var values=fieldExtra.getAsJsonArray("nativeFormTyping");require(!values.isEmpty(),entry.getKey(),"Empty native form typing");for(var v:values)require(words("arceus silvally").contains(v.getAsString()),entry.getKey(),"Invalid native form typing");}
   if(fieldExtra.has("inactiveAbilities")){var values=fieldExtra.getAsJsonArray("inactiveAbilities");for(var a:values)require(a.getAsString().matches("[a-z0-9]+"),entry.getKey(),"Invalid inactive ability");}
   if(fieldExtra.has("statusTypeBypass"))for(var row:fieldExtra.getAsJsonArray("statusTypeBypass")){var r=row.getAsJsonObject();require(r.keySet().equals(words("condition source status")) && r.get("status").getAsString().equals("psn"),entry.getKey(),"Invalid status type bypass");condition(r.get("condition"),fields,entry.getKey());}
   if(fieldExtra.has("suppressedConditionCallbacks"))for(var entryRow:fieldExtra.getAsJsonObject("suppressedConditionCallbacks").entrySet()){var values=entryRow.getValue().getAsJsonArray();require(entryRow.getKey().matches("[a-z0-9]+") && !values.isEmpty(),entry.getKey(),"Invalid condition suppression");Set<String> seen=new HashSet<>();for(var v:values)require(words("onModifyAtk onModifySpA").contains(v.getAsString()) && seen.add(v.getAsString()),entry.getKey(),"Invalid suppressed condition callback");}
   if(fieldExtra.has("abilityDamageCategories"))for(var entryRow:fieldExtra.getAsJsonObject("abilityDamageCategories").entrySet()){var r=entryRow.getValue().getAsJsonObject();require(entryRow.getKey().matches("[a-z0-9]+") && r.keySet().equals(words("categories nativeCategory source")) && words("Physical Special").contains(r.get("nativeCategory").getAsString()) && r.get("source").getAsJsonPrimitive().isString(),entry.getKey(),"Invalid ability damage category");var values=r.getAsJsonArray("categories");require(!values.isEmpty(),entry.getKey(),"Empty ability damage categories");Set<String> seen=new HashSet<>();for(var v:values)require(words("Physical Special").contains(v.getAsString()) && seen.add(v.getAsString()),entry.getKey(),"Invalid damage categories");}
   if(fieldExtra.has("criticalPolicy")){var p=fieldExtra.getAsJsonObject("criticalPolicy");require(p.keySet().equals(words("condition modifier applyScreens hideMessage source")) && numeric(p.get("modifier")) && p.get("modifier").getAsDouble()>0 && p.get("modifier").getAsDouble()<=2 && p.get("applyScreens").getAsJsonPrimitive().isBoolean() && p.get("hideMessage").getAsJsonPrimitive().isBoolean() && p.get("source").getAsJsonPrimitive().isString(),entry.getKey(),"Invalid critical policy");condition(p.get("condition"),fields,entry.getKey());}
   if(fieldExtra.has("clockPolicy")){var c=fieldExtra.getAsJsonObject("clockPolicy");require(words("pauseOverlay source pausedConditions").containsAll(c.keySet()) && c.has("source") && c.has("pauseOverlay") && c.get("pauseOverlay").getAsJsonPrimitive().isBoolean(),entry.getKey(),"Invalid clock policy");
    if(c.has("pausedConditions")){require(c.get("pausedConditions").isJsonArray() && !c.getAsJsonArray("pausedConditions").isEmpty(),entry.getKey(),"Invalid clock policy");for(var paused:c.getAsJsonArray("pausedConditions"))require(words("trickroom gravity wonderroom magicroom").contains(paused.getAsString()),entry.getKey(),"Invalid clock policy");}}
   if(fieldExtra.has("environmentAbilities"))for(var ability:fieldExtra.getAsJsonObject("environmentAbilities").entrySet()){var row=ability.getValue().getAsJsonObject();require(words("quarkdrive protosynthesis").contains(ability.getKey()) && row.keySet().equals(words("boosterMessage callback condition entryCondition expiryMessage messages source")) && words("onTerrainChange onWeatherChange").contains(row.get("callback").getAsString()),entry.getKey(),"Invalid environmental ability");condition(row.get("condition"),fields,entry.getKey());condition(row.get("entryCondition"),fields,entry.getKey());for(String key:List.of("boosterMessage","expiryMessage","source"))require(row.get(key).isJsonPrimitive() && row.getAsJsonPrimitive(key).isString(),entry.getKey(),"Invalid environmental text");require(row.get("messages").isJsonArray() && !row.getAsJsonArray("messages").isEmpty(),entry.getKey(),"Empty environmental messages");for(var message:row.getAsJsonArray("messages")){var r=message.getAsJsonObject();require(r.keySet().equals(words("condition text")) && r.get("text").isJsonPrimitive() && r.getAsJsonPrimitive("text").isString(),entry.getKey(),"Invalid environmental message");condition(r.get("condition"),fields,entry.getKey());}}
   if(fieldExtra.has("itemHandlers"))for(var iid:fieldExtra.getAsJsonObject("itemHandlers").entrySet()){require(iid.getKey().matches("[a-z0-9]+"),entry.getKey(),"Invalid item handler ID");for(var handler:iid.getValue().getAsJsonObject().entrySet()){var r=handler.getValue().getAsJsonObject();require(words("onResidual onStart onModifyMove").contains(handler.getKey()) && r.keySet().equals(words("actions condition mode source")) && words("replace append prepend").contains(r.get("mode").getAsString()),entry.getKey(),"Invalid item handler");condition(r.get("condition"),fields,entry.getKey());actions(r.getAsJsonArray("actions"),fields,entry.getKey());}}
   if(fieldExtra.has("abilityHandlers"))for(var aid:fieldExtra.getAsJsonObject("abilityHandlers").entrySet()){require(aid.getKey().matches("[a-z0-9]+"),entry.getKey(),"Invalid ability handler ID");for(var handler:aid.getValue().getAsJsonObject().entrySet()){var r=handler.getValue().getAsJsonObject();require(words("onStart onResidual onBeforeResidual onEnd onUpdate onAllySwitchIn onSetStatus onAllySetStatus onAnyFaint onDamagingHit onSourceDamagingHit onSourceTryPrimaryHit onTryHit onFoeTryMove onImmunity onBasePower onSourceModifyAccuracy onSourceAccuracy onAllyBasePower onAnyBasePower onModifyAtk onModifySpA onAllyModifyAtk onAllyModifySpA onAllyModifySpD onWeatherChange onModifyDef onModifySpD onModifyDamage onSourceModifyDamage onModifyAccuracy onModifySpe onModifyCritRatio onAllyModifyCritRatio onModifyType onEmergencyExit onDeductPP onSourceAfterFaint onAfterMoveSecondary onModifyMove onAfterEachBoost onAllyTryBoost onAllyTryAddVolatile").contains(handler.getKey()) && r.keySet().equals(words("actions condition mode source")) && words("replace append prepend scaleBoosts").contains(r.get("mode").getAsString()),entry.getKey(),"Invalid ability handler");condition(r.get("condition"),fields,entry.getKey());actions(r.getAsJsonArray("actions"),fields,entry.getKey());}}
   if(fieldExtra.has("customVolatiles"))for(var row:fieldExtra.getAsJsonObject("customVolatiles").entrySet()){var v=row.getValue().getAsJsonObject();require(row.getKey().matches("rejuvenation[a-z0-9]+") && v.keySet().equals(words("actions source")),entry.getKey(),"Invalid custom volatile");actions(v.getAsJsonArray("actions"),fields,entry.getKey());}
   if(fieldExtra.has("rampagePolicy")){var r=fieldExtra.getAsJsonObject("rampagePolicy");require(words("duration noConfusionMoves source").containsAll(r.keySet()) && (!r.has("duration") || integer(r.get("duration"),1,3)) && r.has("noConfusionMoves") && r.get("noConfusionMoves").isJsonArray(),entry.getKey(),"Invalid rampage policy");for(var mid:r.getAsJsonArray("noConfusionMoves"))require(words("outrage thrash petaldance ragingfury").contains(mid.getAsString()),entry.getKey(),"Invalid rampage move");}
   String where=entry.getKey();var f=entry.getValue().getAsJsonObject();
   require(f.get("schemaVersion").getAsInt()==1 && where.equals(f.get("id").getAsString()),where,"Invalid ID/schema");
   for(String k:List.of("name","entryMessage","naturePower","secretPower"))require(f.has(k) && f.get(k).isJsonPrimitive() && f.get(k).getAsJsonPrimitive().isString(),where,"Missing text "+k);
   content(f,fields,where);if(f.has("overlay"))content(f.getAsJsonObject("overlay"),fields,where+"/overlay");
   for(JsonElement element:f.getAsJsonArray("rules")){
    var rule=element.getAsJsonObject();require(EVENTS.contains(rule.get("event").getAsString()),where,"Unknown event");condition(rule.get("condition"),fields,where);actions(rule.getAsJsonArray("actions"),fields,where);
   }
   if(f.has("seedActions"))actions(f.getAsJsonArray("seedActions"),fields,where);
   if(f.has("persistentStatusPolicies"))for(var status:f.getAsJsonObject("persistentStatusPolicies").entrySet()){
    var row=status.getValue().getAsJsonObject();require(status.getKey().equals("ptr") && row.keySet().equals(words("name immuneTypes immuneAbilities sideProtectionAbility drainAbility invertAbility fraction blocksHealing blockedHealingAbilities drainMessage healingFailureMessage source")),where,"Invalid persistent status policy");
    require(numeric(row.get("fraction")) && row.get("fraction").getAsDouble()>0 && row.get("fraction").getAsDouble()<=1 && row.getAsJsonPrimitive("blocksHealing").isBoolean(),where,"Invalid status damage/healing");
    for(String key:List.of("immuneTypes","immuneAbilities","blockedHealingAbilities"))require(row.get(key).isJsonArray() && !row.getAsJsonArray(key).isEmpty(),where,"Missing status IDs");
    for(String key:List.of("name","sideProtectionAbility","drainAbility","invertAbility","drainMessage","healingFailureMessage","source"))require(row.get(key).isJsonPrimitive() && row.getAsJsonPrimitive(key).isString() && !row.get(key).getAsString().isEmpty(),where,"Invalid status text/ability");
   }
   if(f.has("abilityContactPolicies"))for(var policy:f.getAsJsonObject("abilityContactPolicies").entrySet()){
    var row=policy.getValue().getAsJsonObject();require(policy.getKey().equals("perishbody") && row.keySet().equals(words("disabled duration trapDefender forceAttackerStatus message source")) && row.getAsJsonPrimitive("disabled").isBoolean() && row.getAsJsonPrimitive("trapDefender").isBoolean() && numeric(row.get("duration")) && row.get("duration").getAsDouble()==row.get("duration").getAsInt() && row.get("duration").getAsInt()>0 && row.get("duration").getAsInt()<=10 && Set.of("","ptr").contains(row.get("forceAttackerStatus").getAsString()),where,"Invalid contact policy");
   }
   if(f.has("expirationReturnMessage"))require(f.getAsJsonPrimitive("expirationReturnMessage").isString(),where,"Invalid restoration message");
   if(f.has("multiplierPolicy")){
    var row=f.getAsJsonObject("multiplierPolicy");require(row.keySet().equals(words("defaultDifficultyMode defaultFieldFrenzy casualMode casualFactor frenzyBoostFactor frenzyReductionFactor combinedMinimum source")),where,"Invalid multiplier policy");
    for(String key:List.of("defaultDifficultyMode","casualMode"))require(numeric(row.get(key)) && row.get(key).getAsDouble()==row.get(key).getAsInt() && row.get(key).getAsInt()>=0 && row.get(key).getAsInt()<=2,where,"Invalid difficulty defaults");
    require(row.getAsJsonPrimitive("defaultFieldFrenzy").isBoolean(),where,"Invalid Frenzy default");
    for(String key:List.of("casualFactor","frenzyBoostFactor","frenzyReductionFactor","combinedMinimum"))require(numeric(row.get(key)) && row.get(key).getAsDouble()>0 && row.get(key).getAsDouble()<=4,where,"Invalid difficulty factor");
   }
   if(f.has("volatilePolicies"))for(var entryPolicy:f.getAsJsonObject("volatilePolicies").entrySet()){
    var row=entryPolicy.getValue().getAsJsonObject();require(entryPolicy.getKey().equals("nightmare") && row.keySet().equals(words("allowAwake suppressResidual fraction message source")),where,"Unknown volatile policy");
    for(String key:List.of("allowAwake","suppressResidual"))require(row.get(key).isJsonPrimitive() && row.getAsJsonPrimitive(key).isBoolean(),where,"Invalid volatile guard");
    require(numeric(row.get("fraction")) && row.get("fraction").getAsDouble()>0 && row.get("fraction").getAsDouble()<=1 && row.getAsJsonPrimitive("message").isString(),where,"Invalid volatile damage");
   }
   if(f.has("conditionDurations"))for(var entryClock:f.getAsJsonObject("conditionDurations").entrySet()){
    var row=entryClock.getValue().getAsJsonObject();require(words("duration add sourceMoves source choices sourceAbilities").containsAll(row.keySet()) && row.has("duration")!=row.has("add"),where,"Malformed condition clock");
    var value=row.get(row.has("duration")?"duration":"add");require(numeric(value) && value.getAsDouble()>0 && value.getAsDouble()<=20 && value.getAsDouble()==value.getAsInt(),where,"Invalid clock duration");
    require(row.has("sourceMoves") && row.get("sourceMoves").isJsonArray() && !row.getAsJsonArray("sourceMoves").isEmpty(),where,"Missing duration move filter");
    if(row.has("sourceAbilities"))require(row.get("sourceAbilities").isJsonArray(),where,"Invalid duration ability filter");
    if(row.has("choices"))for(var choiceElement:row.getAsJsonArray("choices")){
     var choice=choiceElement.getAsJsonObject();require(words("condition duration randomRange").containsAll(choice.keySet()) && choice.has("duration")!=choice.has("randomRange"),where,"Malformed clock choice");condition(choice.get("condition"),fields,where);
     if(choice.has("duration"))require(numeric(choice.get("duration")) && choice.get("duration").getAsDouble()==choice.get("duration").getAsInt() && choice.get("duration").getAsInt()>0 && choice.get("duration").getAsInt()<=20,where,"Invalid clock choice duration");
     if(choice.has("randomRange")){var range=choice.getAsJsonObject("randomRange");require(range.keySet().equals(words("minimum maximum")),where,"Malformed random clock");for(String key:List.of("minimum","maximum"))require(numeric(range.get(key)) && range.get(key).getAsDouble()==range.get(key).getAsInt(),where,"Invalid random clock bound");require(range.get("minimum").getAsInt()>0 && range.get("maximum").getAsInt()>=range.get("minimum").getAsInt() && range.get("maximum").getAsInt()<=20,where,"Invalid random clock range");}
    }
   }
   if(f.has("mechanics"))mechanics(f.get("mechanics"),fields,where);
   if(f.has("typeComposition")){
    var rows=f.getAsJsonArray("typeComposition");require(!rows.isEmpty() && rows.size()<=16,where,"Invalid type composition");
    for(var e:rows){var r=e.getAsJsonObject();require(words("whenTypes add condition message").containsAll(r.keySet()) && r.has("whenTypes") && r.has("add") && r.has("condition") && r.get("whenTypes").isJsonArray() && !r.getAsJsonArray("whenTypes").isEmpty() && r.getAsJsonArray("whenTypes").size()<=4,where,"Invalid type composition row");
     for(var ty:r.getAsJsonArray("whenTypes"))require(TYPES.contains(ty.getAsString()) && !ty.getAsString().equals("???") && !ty.getAsString().equals("Shadow"),where,"Invalid composition source type");
     require(TYPES.contains(r.get("add").getAsString()) && !r.get("add").getAsString().equals("???") && !r.get("add").getAsString().equals("Shadow") && (!r.has("message") || text(r.get("message"))),where,"Invalid composition added type");condition(r.get("condition"),fields,where);}
   }
   if(f.has("accuracyCrash")){var c=f.getAsJsonObject("accuracyCrash");require(c.keySet().equals(words("fraction messages")) && numeric(c.get("fraction")) && c.get("fraction").getAsDouble()>0 && c.get("fraction").getAsDouble()<=1,where,"Invalid accuracy crash policy");texts(c.get("messages"),where);}
   if(f.has("progression")){var p=f.getAsJsonObject("progression");require(p.get("group").isJsonPrimitive() && integer(p.get("stage"),1,9) && integer(p.get("maximum"),1,9) && p.get("stage").getAsInt()<=p.get("maximum").getAsInt() && (!p.has("statChangeShrinkMessage") || p.get("statChangeShrinkMessage").isJsonPrimitive() && !p.get("statChangeShrinkMessage").getAsString().isEmpty()),entry.getKey(),"Invalid progression");}
   if(f.has("captureModifiers"))for(var capture:f.getAsJsonObject("captureModifiers").entrySet())require(capture.getKey().matches("[a-z0-9_.-]+:[a-z0-9_/.-]+") && numeric(capture.getValue()) && capture.getValue().getAsDouble()>0 && capture.getValue().getAsDouble()<=10,where,"Invalid capture modifier");
   if(f.has("captureEnvironmentModifiers"))for(var element:f.getAsJsonArray("captureEnvironmentModifiers")){
    var row=element.getAsJsonObject();require(row.keySet().equals(words("ball predicate multiplier source")) && row.get("ball").getAsString().matches("[a-z0-9_.-]+:[a-z0-9_/.-]+") && words("underwater night").contains(row.get("predicate").getAsString()) && numeric(row.get("multiplier")) && row.get("multiplier").getAsDouble()>0 && row.get("multiplier").getAsDouble()<=10,where,"Invalid capture environment rule");
   }
   if(f.has("hazardPolicy")){var h=f.getAsJsonObject("hazardPolicy");var shape=Map.of("spikes",words("type affectsAirborne message"),"stealthrock",words("type cycleTypes multiplier message"),"stickyweb",words("stages"),"toxicspikes",words("keepOnPoisonType"));
    require(h.has("source") && h.get("source").isJsonPrimitive() && words("source cleared suspended spikes stealthrock stickyweb toxicspikes").containsAll(h.keySet()) && (!h.has("suspended") || h.get("suspended").getAsBoolean()),where,"Invalid hazard policy");
    if(h.has("cleared")){require(h.get("cleared").isJsonArray() && !h.getAsJsonArray("cleared").isEmpty(),where,"Invalid hazard policy");for(var cleared:h.getAsJsonArray("cleared"))require(shape.containsKey(cleared.getAsString()),where,"Invalid hazard policy");}
    for(var entryShape:shape.entrySet()){if(!h.has(entryShape.getKey()))continue;var r=h.getAsJsonObject(entryShape.getKey());
     require(!r.isEmpty() && entryShape.getValue().containsAll(r.keySet()) && !(r.has("type") && r.has("cycleTypes")) && (!r.has("type") || r.get("type").getAsString().matches("[A-Z][a-z]+")) && (!r.has("message") || !r.get("message").getAsString().isEmpty()) && (!r.has("multiplier") || (numeric(r.get("multiplier")) && r.get("multiplier").getAsDouble()>0)) && (!r.has("affectsAirborne") || r.get("affectsAirborne").getAsBoolean()) && (!r.has("keepOnPoisonType") || r.get("keepOnPoisonType").getAsBoolean()) && (!r.has("stages") || integer(r.get("stages"),-6,-1)),where,"Invalid hazard policy row");
     if(r.has("cycleTypes"))for(var type:r.getAsJsonArray("cycleTypes"))require(type.getAsString().matches("[A-Z][a-z]+"),where,"Invalid hazard policy row");}}
   if(f.has("entryWishes"))for(var wish:f.getAsJsonObject("entryWishes").entrySet()){var row=wish.getValue().getAsJsonObject();require(words("healingwish lunardance").contains(wish.getKey()) && row.keySet().equals(Set.of("boosts","message","source")) && !row.get("message").getAsString().isEmpty() && row.get("source").isJsonPrimitive(),where,"Invalid entry wish");stats(row.getAsJsonObject("boosts"),where);for(var boost:row.getAsJsonObject("boosts").entrySet())require(words("atk def spa spd spe").contains(boost.getKey()) && boost.getValue().getAsInt()>0,where,"Invalid entry wish");}
   if(f.has("silentVolatileEnds")){require(f.get("silentVolatileEnds").isJsonArray() && !f.getAsJsonArray("silentVolatileEnds").isEmpty(),where,"Invalid silent volatile end");for(var silent:f.getAsJsonArray("silentVolatileEnds"))require(silent.getAsString().equals("slowstart"),where,"Invalid silent volatile end");}
   if(f.has("effectivenessOverrides"))for(var override:f.getAsJsonArray("effectivenessOverrides")){var row=override.getAsJsonObject();require(row.keySet().equals(Set.of("condition","value","source")) && integer(row.get("value"),-3,3) && row.get("source").isJsonPrimitive(),where,"Invalid effectiveness override");condition(row.get("condition"),fields,where);}
   if(f.has("revivalBlessing")){var revival=f.getAsJsonObject("revivalBlessing");require(revival.keySet().equals(Set.of("fraction","source")) && numeric(revival.get("fraction")) && revival.get("fraction").getAsDouble()>0 && revival.get("fraction").getAsDouble()<=1 && revival.get("source").isJsonPrimitive(),where,"Invalid Revival Blessing policy");}
   if(f.has("priorityBlockingAbilities"))for(var aid:f.getAsJsonArray("priorityBlockingAbilities"))require(aid.getAsString().matches("[a-z0-9]+"),where,"Invalid priority-blocking ability");
   if(f.has("volatileMoveLocks"))for(var lock:f.getAsJsonObject("volatileMoveLocks").entrySet()){var row=lock.getValue().getAsJsonObject();require(lock.getKey().matches("[a-z0-9]+") && row.keySet().equals(Set.of("move","source")) && row.get("move").getAsString().matches("[a-z0-9]+") && row.get("source").isJsonPrimitive(),where,"Invalid volatile move lock");}
   if(f.has("timedWeatherText"))for(var timed:f.getAsJsonObject("timedWeatherText").entrySet()){var row=timed.getValue().getAsJsonObject();require(words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(timed.getKey()) && row.keySet().equals(Set.of("startMessage","endMessage","source")),where,"Invalid timed weather text");for(var text:row.entrySet())require(text.getValue().isJsonPrimitive() && !text.getValue().getAsString().isEmpty(),where,"Invalid timed weather text");}
   if(f.has("weatherRainbow")){var r=f.getAsJsonObject("weatherRainbow");require(r.keySet().equals(Set.of("field","groups","message","refreshMessage","baseDuration","extendedDuration","extendingItems","source")) && fields.has(r.get("field").getAsString()) && r.get("groups").isJsonArray() && r.getAsJsonArray("groups").size()==2 && integer(r.get("baseDuration"),1,20) && integer(r.get("extendedDuration"),1,20),where,"Invalid weather rainbow policy");
    var seen=new java.util.HashSet<String>();for(var group:r.getAsJsonArray("groups")){require(group.isJsonArray() && !group.getAsJsonArray().isEmpty(),where,"Invalid weather rainbow policy");for(var weather:group.getAsJsonArray())require(words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(weather.getAsString()) && seen.add(weather.getAsString()),where,"Invalid weather rainbow policy");}
    for(var key:List.of("message","refreshMessage","source"))require(r.get(key).isJsonPrimitive() && !r.get(key).getAsString().isEmpty(),where,"Invalid weather rainbow policy");
    for(var item:r.getAsJsonObject("extendingItems").entrySet())require(seen.contains(item.getKey()) && item.getValue().isJsonPrimitive() && !item.getValue().getAsString().isEmpty(),where,"Invalid weather rainbow policy");}
   if(f.has("weatherConversions"))for(var conversion:f.getAsJsonObject("weatherConversions").entrySet())require(words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(conversion.getKey()) && words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(conversion.getValue().getAsString()) && !conversion.getKey().equals(conversion.getValue().getAsString()),where,"Invalid weather conversion");
   if(f.has("abilityAbsorptions"))for(var entryPolicy:f.getAsJsonObject("abilityAbsorptions").entrySet()){
    var row=entryPolicy.getValue().getAsJsonObject();require(words("type stat boosts healFractions cycle maximizeOverlay source").containsAll(row.keySet()) && row.has("boosts")!=row.has("healFractions"),where,"Malformed absorption policy");
    require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(row.get("type").getAsString()),where,"Invalid absorption type");
    var values=row.getAsJsonArray(row.has("boosts")?"boosts":"healFractions");require(!values.isEmpty(),where,"Missing absorption values");
    for(var value:values)require(numeric(value) && value.getAsDouble()>=0 && value.getAsDouble()<=(row.has("boosts")?6:1),where,"Invalid absorption value");
    if(row.has("boosts"))require(words("atk def spa spd spe").contains(row.get("stat").getAsString()),where,"Invalid absorption stat");
    if(row.has("maximizeOverlay"))require(fields.has(row.get("maximizeOverlay").getAsString()),where,"Invalid absorption overlay");
   }
   if(f.has("statPools")){
    var pools=f.getAsJsonObject("statPools");require(pools.keySet().equals(words("offensiveSpecial defensiveSpecial borrowedOffense source")),where,"Malformed shared stat keys");
    for(var row:pools.getAsJsonObject("borrowedOffense").entrySet()){var value=row.getValue().getAsJsonObject();require(row.getKey().matches("[a-z0-9]+") && value.keySet().equals(words("selection modifierSelection")) && value.get("selection").getAsString().equals("staged") && value.get("modifierSelection").getAsString().equals("modifiersOnly"),where,"Invalid borrowed stat selection");}
    for(String key:List.of("offensiveSpecial","defensiveSpecial")){var values=pools.getAsJsonArray(key);require(values.size()==2 && new HashSet<>(values.asList()).equals(Set.of(new JsonPrimitive("spa"),new JsonPrimitive("spd"))),where,"Invalid shared Special stats");}
   }
   if(f.has("trapping")){
    var t=f.getAsJsonObject("trapping");require(words("divisors moveIncrements statLoss immuneAbilities octolockAmount source").containsAll(t.keySet()),where,"Malformed trapping keys");
    require(t.get("divisors").equals(JsonParser.parseString("[8,6,4,3,2]")),where,"Invalid binding divisor table");
    for(var v:t.getAsJsonObject("moveIncrements").entrySet())require(numeric(v.getValue()) && v.getValue().getAsInt()>=0 && v.getValue().getAsInt()<=3,where,"Invalid binding increment");
    for(var v:t.getAsJsonObject("statLoss").entrySet()){require(v.getValue().isJsonArray() && !v.getValue().getAsJsonArray().isEmpty(),where,"Missing binding stats");for(var s:v.getValue().getAsJsonArray())require(words("atk def spa spd spe accuracy evasion").contains(s.getAsString()),where,"Invalid binding stat");}
    if(t.has("octolockAmount"))require(numeric(t.get("octolockAmount")) && Set.of(-1,-2).contains(t.get("octolockAmount").getAsInt()),where,"Invalid Octolock amount");
   }
   if(f.has("grounding")){
    var g=f.getAsJsonObject("grounding");require(g.keySet().equals(words("airborneAbilities forceGroundingItems source")),where,"Malformed grounding policy");
    for(String key:List.of("airborneAbilities","forceGroundingItems"))for(var id:g.getAsJsonArray(key))require(id.isJsonPrimitive() && id.getAsString().matches("[a-z0-9]+"),where,"Invalid grounding ID");
   }
   if(f.has("gravityUsableMoves"))for(var id:f.getAsJsonArray("gravityUsableMoves"))require(id.isJsonPrimitive() && id.getAsString().matches("[a-z0-9]+"),where,"Invalid gravity move");
   if(f.has("terrainPolicy")){
    var p=f.getAsJsonObject("terrainPolicy");require(words("blockedMessage blockedFields moveDurations abilityDurations source clearOverlayOnEntry").containsAll(p.keySet()),where,"Malformed terrain policy");
    if(p.has("clearOverlayOnEntry"))require(p.getAsJsonPrimitive("clearOverlayOnEntry").isBoolean(),where,"Invalid overlay clearing policy");
    if(p.has("blockedFields"))for(var id:p.getAsJsonArray("blockedFields"))require(fields.has(id.getAsString()),where,"Invalid blocked terrain");
    for(String key:List.of("moveDurations","abilityDurations"))if(p.has(key))for(var d:p.getAsJsonObject(key).entrySet())require(fields.has(d.getKey()) && numeric(d.getValue()) && d.getValue().getAsInt()>0 && d.getValue().getAsInt()<=20,where,"Invalid terrain duration");
   }
   if(f.has("healing")){
    var h=f.getAsJsonObject("healing");require(h.keySet().equals(words("rootFactor agentMultipliers overlayAgents moveMultipliers harmfulAgents liquidOozeFactor drainStatLoss")),where,"Malformed healing configuration");
    for(String key:List.of("rootFactor","liquidOozeFactor"))require(numeric(h.get(key)) && h.get(key).getAsDouble()>0,where,"Invalid healing factor");
    for(String key:List.of("agentMultipliers","moveMultipliers"))for(var m:h.getAsJsonObject(key).entrySet())require(numeric(m.getValue()) && m.getValue().getAsDouble()>0,where,"Invalid healing multiplier");
    require(h.get("drainStatLoss").isJsonPrimitive() && h.get("drainStatLoss").getAsJsonPrimitive().isBoolean(),where,"Invalid drain stat loss");
    for(var m:h.getAsJsonObject("harmfulAgents").entrySet()){var v=m.getValue().getAsJsonObject();require(v.keySet().equals(words("respectMagicGuard message")) && v.get("respectMagicGuard").getAsJsonPrimitive().isBoolean() && v.get("message").getAsJsonPrimitive().isString(),where,"Malformed harmful healing");}
    for(var agent:h.getAsJsonArray("overlayAgents"))require(words("drain leechseed ingrain aquaring strengthsap").contains(agent.getAsString()),where,"Unknown absorbed healing agent");
   }
   if(f.has("suppressedAbilityCallbacks"))for(var entryCallback:f.getAsJsonObject("suppressedAbilityCallbacks").entrySet())require((entryCallback.getValue().equals(JsonParser.parseString("[\"onTryHit\"]")) || entryCallback.getValue().equals(JsonParser.parseString("[\"onImmunity\"]"))),where,"Unsupported ability callback");
   if(f.has("partyRoles")){
    var roles=f.getAsJsonObject("partyRoles");require(roles.keySet().equals(words("tailRole frontRole frontCount leaderRole preferAbilities preferItems remaining")),where,"Malformed party roles");
    for(var remaining:roles.getAsJsonArray("remaining")){var r=remaining.getAsJsonObject();require(r.has("role") && r.get("role").isJsonPrimitive(),where,"Missing party role");for(var stat:r.getAsJsonArray("maxStats"))require(words("atk def spa spd spe").contains(stat.getAsString()),where,"Invalid role stat");}
    for(String mode:List.of("singles","doubles"))require(roles.getAsJsonObject("frontCount").get(mode).getAsInt()>0,where,"Invalid front role count");
   }
   if(f.has("typeChart"))for(var element:f.getAsJsonArray("typeChart")){
    var row=element.getAsJsonObject();require(row.keySet().equals(words("attackType defenseType value condition source")),where,"Invalid type chart keys");
    var value=row.get("value");require(value.isJsonPrimitive() && ((numeric(value) && Set.of(-1.0,0.0,1.0).contains(value.getAsDouble())) || value.getAsString().equals("immune")),where,"Invalid type chart result");
    for(String key:List.of("attackType","defenseType"))require(words("* Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(row.get(key).getAsString()),where,"Invalid type chart type");
    condition(row.get("condition"),fields,where);
   }
  }
  for(JsonElement element:catalog.getAsJsonArray("mappings")){
   var rule=element.getAsJsonObject();require(fields.has(rule.get("field").getAsString()),"mapping","Missing field");
   require(words("biome tag dimension submerged maxY skyVisible minDepth field reason substrate").containsAll(rule.keySet()),"mapping","Unknown predicate");
   // A substrate is the dormant field beneath the selected one: a known, non-Indoor field other than the field itself.
   if(rule.has("substrate")){var sub=rule.get("substrate");require(sub.isJsonPrimitive() && sub.getAsJsonPrimitive().isString() && fields.has(sub.getAsString()) && !sub.getAsString().equals("rejuvenation:indoor") && !sub.getAsString().equals(rule.get("field").getAsString()),"mapping","Invalid substrate layer");}
  }
  // Structure rows name exactly one structure registry ID or structure tag; unmapped structures fall through to biome rules.
  if(catalog.has("structures"))for(JsonElement element:catalog.getAsJsonArray("structures")){
   require(element.isJsonObject(),"structure","Invalid structure mapping");var rule=element.getAsJsonObject();
   require(words("structure tag field reason containment").containsAll(rule.keySet()) && rule.has("field") && fields.has(rule.get("field").getAsString()),"structure","Invalid structure mapping");
   if(rule.has("containment")){
    require(rule.get("containment").isJsonObject(),"structure","Invalid structure containment");var c=rule.getAsJsonObject("containment");
    require(c.has("mode") && c.get("mode").isJsonPrimitive(),"structure","Invalid structure containment mode");
    if(c.get("mode").getAsString().equals("pieces"))require(c.size()==1,"structure","A pieces containment has no margins");
    else{require(c.get("mode").getAsString().equals("footprint") && c.keySet().equals(words("mode horizontal above below")),"structure","Invalid structure containment");
     require(integer(c.get("horizontal"),0,StructureGeometry.MAX_HORIZONTAL) && integer(c.get("above"),0,StructureGeometry.MAX_ABOVE) && integer(c.get("below"),0,StructureGeometry.MAX_BELOW),"structure","Structure containment margin out of range");}
   }
   require(rule.has("structure")!=rule.has("tag"),"structure","A structure mapping names exactly one structure or tag");
   String id=(rule.has("structure")?rule.get("structure"):rule.get("tag")).getAsString();
   require(id.matches("[a-z0-9_.-]+:[a-z0-9_./-]+"),"structure","Invalid structure identifier "+id);
  }
 }
 private static void content(JsonObject data,JsonObject fields,String where){
  for(var entry:data.getAsJsonObject("moves").entrySet()){
   var move=entry.getValue().getAsJsonObject();String at=where+"/"+entry.getKey();
   for(String key:List.of("multiplier","accuracy"))if(move.has(key)){var n=move.get(key);require(numeric(n) && n.getAsDouble()>=0 && (!key.equals("accuracy") || n.getAsDouble()<=100),at,"Invalid "+key);}
   if(move.has("after"))actions(move.getAsJsonArray("after"),fields,at);
   if(move.has("transition")){var t=move.getAsJsonObject("transition");require(fields.has(t.get("field").getAsString()),at,"Missing transition target");condition(t.get("condition"),fields,at);if(t.has("after"))actions(t.getAsJsonArray("after"),fields,at);}
  }
  for(var element:data.getAsJsonArray("types")){var t=element.getAsJsonObject();condition(t.get("match"),fields,where);condition(t.get("condition"),fields,where);if(t.has("after"))actions(t.getAsJsonArray("after"),fields,where);}
 }
 private static void condition(JsonElement e,JsonObject fields,String where){
  require(e!=null && e.isJsonObject() && e.getAsJsonObject().size()==1,where,"Malformed condition");
  var c=e.getAsJsonObject();String k=c.keySet().iterator().next();var v=c.get(k);require(CONDITIONS.contains(k),where,"Unknown condition "+k);
  if(k.equals("all") || k.equals("any")){require(v.isJsonArray() && !v.getAsJsonArray().isEmpty(),where,"Empty Boolean group");for(var a:v.getAsJsonArray())condition(a,fields,where);}
  else if(k.equals("canHeal")){require(v.isJsonObject() && v.getAsJsonObject().keySet().equals(words("who value")),where,"Invalid healing predicate");var h=v.getAsJsonObject();require(words("user target").contains(h.get("who").getAsString()) && h.get("value").isJsonPrimitive() && h.getAsJsonPrimitive("value").isBoolean(),where,"Invalid healing predicate");}
  else if(k.equals("not"))condition(v,fields,where);
  else if(Set.of("field","backup","overlay").contains(k))require(fields.has(v.getAsString()),where,"Unknown condition field");
  else if(words("always foe missed weatherActive fullHealing foeFainted samePokemon hasAlly transformed itemStealable statsLowered selfInflicted abilityChangedType holderAllied variableMultihit holderIsUser connected accuracyMiss damageDealt drainHealed canFlinch baseCanFlinch sheerForce allyCanHeal oneHitKO zMove").contains(k))require(v.isJsonPrimitive() && v.getAsJsonPrimitive().isBoolean(),where,"Expected Boolean condition");
  else if(k.equals("pokemonFlag")){var r=v.getAsJsonObject();require(r.keySet().equals(words("who id value")) && words("user target").contains(r.get("who").getAsString()) && r.get("id").getAsString().matches("[a-z][a-z0-9_]*") && r.get("value").getAsJsonPrimitive().isBoolean(),where,"Invalid Pokemon flag predicate");}
  else if(k.equals("statSumComparison")){var r=v.getAsJsonObject();require(r.keySet().equals(words("left right group op")) && words("foes allies").contains(r.get("group").getAsString()) && words("> >= < <= ==").contains(r.get("op").getAsString()) && words("atk def spa spd spe").contains(r.get("left").getAsString()) && words("atk def spa spd spe").contains(r.get("right").getAsString()),where,"Invalid stat sum comparison");}
  else if(k.equals("volatileSourceMove")){var a=v.getAsJsonObject();require(a.keySet().equals(words("who id move")) && words("user target").contains(a.get("who").getAsString()) && a.get("id").getAsString().matches("[a-z0-9]+") && a.get("move").getAsString().matches("[a-z0-9]+"),where,"Invalid volatile source move");}
  else if(k.equals("immunityType")){require(v.isJsonArray() && !v.getAsJsonArray().isEmpty(),where,"Invalid immunity type");for(var t:v.getAsJsonArray())require(t.isJsonPrimitive() && words("hail sandstorm shadowsky").contains(t.getAsString()),where,"Invalid immunity type");}
  else if(k.equals("pseudoWeather")){var a=v.getAsJsonObject();require(a.keySet().equals(words("id value")) && words("gravity mudsport trickroom magicroom wonderroom iondeluge").contains(a.get("id").getAsString()) && a.get("value").getAsJsonPrimitive().isBoolean(),where,"Invalid field condition");}
  else if(k.equals("chance"))probability(v.getAsJsonObject(),where);
  else if(k.equals("effectId") || k.equals("calledBy"))require(v.isJsonPrimitive() && v.getAsString().matches("[a-z0-9]+"),where,"Invalid effect identifier predicate");
  else if(k.equals("boostStage")){var a=v.getAsJsonObject();require(a.keySet().equals(words("who stat op value")) && words("user target").contains(a.get("who").getAsString()) && words("atk def spa spd spe accuracy evasion").contains(a.get("stat").getAsString()) && words("> >= < <= ==").contains(a.get("op").getAsString()) && integer(a.get("value"),-6,6),where,"Invalid stage predicate");}
  else if(k.equals("actorType")){var a=v.getAsJsonObject();require(a.has("who") && words("user target").contains(a.get("who").getAsString()) && a.has("values") && a.get("values").isJsonArray() && !a.getAsJsonArray("values").isEmpty(),where,"Invalid actor type predicate");for(var t:a.getAsJsonArray("values"))require(words("wild player npc").contains(t.getAsString()),where,"Invalid actor type predicate");}
  else if(k.equals("holderAbilityState"))require(v.isJsonPrimitive() && words("resisted").contains(v.getAsString()),where,"Invalid ability state predicate");
  else if(k.equals("baseMoveType"))require(v.isJsonPrimitive() && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy").contains(v.getAsString()),where,"Invalid base move type");
  else if(words("contact wild usableMove pokemonActive").contains(k)){var a=v.getAsJsonObject();require(a.has("who") && words("user target").contains(a.get("who").getAsString()) && (!k.equals("wild") || a.has("value") && a.get("value").getAsJsonPrimitive().isBoolean()),where,"Invalid actor/contact predicate");}
  else if(k.equals("faster"))require(v.isJsonObject() && v.getAsJsonObject().has("stored") && v.getAsJsonObject().get("stored").getAsJsonPrimitive().isBoolean(),where,"Malformed speed comparison");
  else if(k.equals("damageSource")){require(v.isJsonArray() && !v.getAsJsonArray().isEmpty(),where,"Missing damage source");for(var damageSource:v.getAsJsonArray())require(damageSource.getAsString().matches("[a-z0-9]+"),where,"Invalid damage source");}
  else if(k.equals("startedCondition")){require(v.isJsonArray() && !v.getAsJsonArray().isEmpty(),where,"Missing started condition");for(var started:v.getAsJsonArray())require(words("mist safeguard luckychant reflect lightscreen auroraveil tailwind spikes toxicspikes stealthrock stickyweb").contains(started.getAsString()),where,"Unknown started condition");}
  else if(k.equals("incomingWeather")){require(v.isJsonArray() && !v.getAsJsonArray().isEmpty(),where,"Missing incoming weather");for(var weather:v.getAsJsonArray())require(words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(weather.getAsString()),where,"Unknown incoming weather");}
  else if(k.equals("weatherFor")){require(v.isJsonObject(),where,"Malformed subject weather");var a=v.getAsJsonObject();require(a.has("who") && words("user target").contains(a.get("who").getAsString()),where,"Invalid weather subject");require(a.has("values") && a.get("values").isJsonArray() && !a.getAsJsonArray("values").isEmpty(),where,"Missing subject weather");for(var weather:a.getAsJsonArray("values"))require(words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(weather.getAsString()),where,"Unknown subject weather");}
  else if(words("role type species form formName grounded volatile ability effectiveAbility sideAbility allyAbility item sideItem semiInvulnerable lastMove").contains(k)){
   var a=v.getAsJsonObject();require(words("user target").contains(a.get("who").getAsString()),where,"Invalid condition subject");
   if(words("ability effectiveAbility sideAbility allyAbility item sideItem lastMove").contains(k))require(a.has("values") && a.get("values").isJsonArray() && !a.getAsJsonArray("values").isEmpty(),where,"Empty ID list");
   if(k.equals("role"))require(a.has("value") && a.get("value").getAsString().matches("[a-z][a-z0-9_]*"),where,"Invalid role identifier");
   if(k.equals("formName"))require(a.has("value") && a.get("value").isJsonPrimitive() && a.getAsJsonPrimitive("value").isString(),where,"Invalid form name");
  }
  else if(Set.of("counter","priority","hp","effectiveness","turnsActive","level","value","basePower","hitEffectiveness").contains(k)){
   var a=v.getAsJsonObject();require(words("> >= < <= ==").contains(a.get("op").getAsString()),where,"Invalid comparator");require(numeric(a.get(k.equals("hp")?"fraction":"value")),where,"Invalid number");
   if(k.equals("counter"))require(a.get("index").getAsInt()>=1 && a.get("index").getAsInt()<=5,where,"Invalid counter");
  }
 }
 private static boolean text(JsonElement e){return e!=null && e.isJsonPrimitive() && e.getAsJsonPrimitive().isString() && !e.getAsString().isEmpty() && e.getAsString().length()<=240;}
 private static void texts(JsonElement e,String where){require(e!=null && e.isJsonArray() && !e.getAsJsonArray().isEmpty() && e.getAsJsonArray().size()<=4,where,"Invalid message list");for(var t:e.getAsJsonArray())require(text(t),where,"Invalid message");}
 private static void exact(JsonElement e,String keys,String where){require(e!=null && e.isJsonObject() && e.getAsJsonObject().keySet().equals(words(keys)),where,"Malformed "+where);}
 private static void moveIds(JsonElement e,String where){require(e!=null && e.isJsonArray() && e.getAsJsonArray().size()<=64,where,"Invalid move list");var seen=new HashSet<String>();for(var m:e.getAsJsonArray())require(m.isJsonPrimitive() && m.getAsString().matches("[a-z0-9]+") && seen.add(m.getAsString()),where,"Invalid move identifier");}
 private static final Set<String> TYPES=words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???");
 /** Data-configured field mechanics (Sculk Warning, Creaking Distraction, Piglin Bloodlust): closed shapes, bounded numbers and texts. */
 private static void mechanics(JsonElement element,JsonObject fields,String where){
  require(element!=null && element.isJsonObject() && !element.getAsJsonObject().isEmpty() && words("sculkWarning creakingDistraction bloodlust").containsAll(element.getAsJsonObject().keySet()),where,"Invalid field mechanics");
  var m=element.getAsJsonObject();
  if(m.has("sculkWarning")){
   var w=m.getAsJsonObject("sculkWarning");String at=where+"/sculkWarning";
   exact(w,"counter maximum darknessAt retaliationAt resetTo thresholds amounts overrides sound seismic calming messages stages rattled retaliation immunities seedMessage",at);
   int max=w.get("maximum").getAsInt();require(integer(w.get("counter"),1,5) && integer(w.get("maximum"),2,8) && integer(w.get("darknessAt"),1,max) && integer(w.get("retaliationAt"),w.get("darknessAt").getAsInt(),max) && integer(w.get("resetTo"),0,w.get("retaliationAt").getAsInt()-1),at,"Invalid scale");
   exact(w.get("thresholds"),"moderate major",at+"/thresholds");var th=w.getAsJsonObject("thresholds");require(integer(th.get("moderate"),1,1000) && integer(th.get("major"),th.get("moderate").getAsInt(),1000),at,"Invalid thresholds");
   exact(w.get("amounts"),"moderate major calming seed",at+"/amounts");var am=w.getAsJsonObject("amounts");require(integer(am.get("moderate"),0,4) && integer(am.get("major"),0,4) && integer(am.get("calming"),-4,0) && integer(am.get("seed"),0,4),at,"Invalid amounts");
   require(w.get("overrides").isJsonObject() && w.getAsJsonObject("overrides").size()<=64,at,"Invalid overrides");
   for(var o:w.getAsJsonObject("overrides").entrySet()){require(o.getKey().matches("[a-z0-9]+"),at,"Invalid override move");exact(o.getValue(),"amount message",at+"/override");require(integer(o.getValue().getAsJsonObject().get("amount"),0,4) && text(o.getValue().getAsJsonObject().get("message")),at,"Invalid override");}
   exact(w.get("sound"),"amount message categories",at+"/sound");var so=w.getAsJsonObject("sound");require(integer(so.get("amount"),0,4) && text(so.get("message")) && so.get("categories").isJsonArray() && !so.getAsJsonArray("categories").isEmpty(),at,"Invalid sound policy");for(var c:so.getAsJsonArray("categories"))require(words("Physical Special Status").contains(c.getAsString()),at,"Invalid sound category");
   exact(w.get("seismic"),"amount message moves",at+"/seismic");var se=w.getAsJsonObject("seismic");require(integer(se.get("amount"),0,4) && text(se.get("message")),at,"Invalid seismic policy");moveIds(se.get("moves"),at);
   exact(w.get("calming"),"moves messages defaultMessage",at+"/calming");var ca=w.getAsJsonObject("calming");moveIds(ca.get("moves"),at);require(text(ca.get("defaultMessage")) && ca.get("messages").isJsonObject(),at,"Invalid calming group");
   for(var c:ca.getAsJsonObject("messages").entrySet())require(text(c.getValue()) && StreamSupport.stream(ca.getAsJsonArray("moves").spliterator(),false).anyMatch(x->x.getAsString().equals(c.getKey())),at,"Invalid calming message");
   exact(w.get("messages"),"moderate major gimmick recede",at+"/messages");for(var v:w.getAsJsonObject("messages").entrySet())require(text(v.getValue()),at,"Invalid message");
   require(w.get("stages").isJsonObject(),at,"Invalid stages");for(var s:w.getAsJsonObject("stages").entrySet()){require(s.getKey().matches("[1-8]") && Integer.parseInt(s.getKey())<=max,at,"Invalid stage");texts(s.getValue(),at);}
   exact(w.get("rattled"),"ability stats message",at+"/rattled");var ra=w.getAsJsonObject("rattled");require(ra.get("ability").getAsString().matches("[a-z0-9]+") && text(ra.get("message")),at,"Invalid Rattled");stats(ra.getAsJsonObject("stats"),at);
   exact(w.get("retaliation"),"announce fraction resetMessage",at+"/retaliation");var re=w.getAsJsonObject("retaliation");require(text(re.get("announce")) && text(re.get("resetMessage")) && numeric(re.get("fraction")) && re.get("fraction").getAsDouble()>0 && re.get("fraction").getAsDouble()<=1,at,"Invalid retaliation");
   exact(w.get("immunities"),"abilities types",at+"/immunities");var im=w.getAsJsonObject("immunities");
   for(var a:im.getAsJsonObject("abilities").entrySet())require(a.getKey().matches("[a-z0-9]+") && text(a.getValue()),at,"Invalid immunity ability");
   for(var ty:im.getAsJsonObject("types").entrySet())require(TYPES.contains(ty.getKey()) && text(ty.getValue()),at,"Invalid immunity type");
   require(text(w.get("seedMessage")),at,"Invalid seed message");
  }
  if(m.has("creakingDistraction")){
   var d=m.getAsJsonObject("creakingDistraction");String at=where+"/creakingDistraction";exact(d,"maximum damageFraction stages resetMessage subsidedMessage",at);int max=d.get("maximum").getAsInt();
   require(integer(d.get("maximum"),2,8) && numeric(d.get("damageFraction")) && d.get("damageFraction").getAsDouble()>0 && d.get("damageFraction").getAsDouble()<=1 && text(d.get("resetMessage")) && text(d.get("subsidedMessage")) && d.get("stages").isJsonObject(),at,"Invalid Creaking Distraction");
   for(var s:d.getAsJsonObject("stages").entrySet()){require(s.getKey().matches("[1-8]") && Integer.parseInt(s.getKey())<=max,at,"Invalid stage");texts(s.getValue(),at);}
  }
  if(m.has("bloodlust")){var l=m.getAsJsonObject("bloodlust");String at=where+"/bloodlust";exact(l,"stat amount message",at);require(words("atk def spa spd spe").contains(l.get("stat").getAsString()) && integer(l.get("amount"),1,3) && text(l.get("message")),at,"Invalid Piglin Bloodlust");}
 }
 private static void actions(JsonArray list,JsonObject fields,String where){
  require(list!=null,where,"Missing actions");
  for(var element:list){var a=element.getAsJsonObject();String op=a.get("op").getAsString();require(ACTIONS.contains(op),where,"Unknown action "+op);
   if(a.has("who"))require(words("user target").contains(a.get("who").getAsString()),where,"Invalid action subject");
   if(op.equals("conditional")){condition(a.get("condition"),fields,where);actions(a.getAsJsonArray("actions"),fields,where);}
   if(op.equals("accuracyPenalty"))require(words("op factor attribute who").containsAll(a.keySet()) && numeric(a.get("factor")) && a.get("factor").getAsDouble()>0 && a.get("factor").getAsDouble()<=1 && (!a.has("attribute") || a.get("attribute").getAsJsonPrimitive().isBoolean()),where,"Invalid accuracy penalty");
   if(op.equals("mechanic"))require(a.keySet().equals(words("op kind event")) && a.get("kind").getAsString().equals("sculkWarning") && a.get("event").getAsString().equals("seed"),where,"Invalid mechanic event");
   if(a.has("messagePlacement"))require(words("before after").contains(a.get("messagePlacement").getAsString()),where,"Invalid message placement");
   if(op.equals("boost") && a.has("source"))require(a.get("source").getAsString().equals("environment"),where,"Invalid boost source");
   if(op.equals("hazardBurst")){require(a.has("id") && words("spikes stealthrock stickyweb toxicspikes").contains(a.get("id").getAsString()) && a.has("messages") && a.get("messages").isJsonArray() && !a.getAsJsonArray("messages").isEmpty() && words("op id messages type fraction perLayer grounded immuneTypes poison boosts").containsAll(a.keySet()),where,"Invalid hazard burst");
    for(var text:a.getAsJsonArray("messages"))require(text.isJsonPrimitive() && !text.getAsString().isEmpty(),where,"Invalid hazard burst");
    if(a.has("boosts")){stats(a.getAsJsonObject("boosts"),where);require(!a.has("fraction"),where,"Invalid hazard burst effect");}else require(numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1,where,"Invalid hazard burst effect");
    for(String key:List.of("perLayer","grounded","poison"))require(!a.has(key) || a.get(key).getAsJsonPrimitive().isBoolean(),where,"Invalid hazard burst filter");
    require(!a.has("type") || a.get("type").getAsString().matches("[A-Z][a-z]+"),where,"Invalid hazard burst filter");if(a.has("immuneTypes"))for(var type:a.getAsJsonArray("immuneTypes"))require(type.getAsString().matches("[A-Z][a-z]+"),where,"Invalid hazard burst filter");}
   if(op.equals("typedDamage") && a.has("direct"))require(a.get("direct").getAsJsonPrimitive().isBoolean(),where,"Invalid direct damage policy");
   if(op.equals("setPokemonFlag"))require(a.get("id").getAsString().matches("[a-z][a-z0-9_]*") && a.get("value").getAsJsonPrimitive().isBoolean(),where,"Invalid Pokemon flag action");
   if(op.equals("setWeather") && a.has("onSuccess"))actions(a.getAsJsonArray("onSuccess"),fields,where);
   if(op.equals("setWeather") && a.has("duration"))require(integer(a.get("duration"),1,20) && !a.has("keepDuration"),where,"Invalid weather duration");
   if(op.equals("setWeather") && a.has("keepDuration"))require(a.get("keepDuration").isJsonPrimitive() && a.get("keepDuration").getAsJsonPrimitive().isBoolean() && a.get("keepDuration").getAsBoolean(),where,"Invalid weather clock policy");
   if(a.has("scaleField"))require(words("multiply cyclePower randomPower").contains(op) && a.getAsJsonPrimitive("scaleField").isBoolean(),where,"Invalid field scaling flag");
   if(op.equals("moveBehavior") && a.get("recipe").getAsString().equals("partialProtection")){require(a.has("conditions") && a.get("conditions").isJsonArray() && !a.getAsJsonArray("conditions").isEmpty() && numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1 && a.get("message").isJsonPrimitive() && a.getAsJsonPrimitive("message").isString(),where,"Invalid partial protection");for(var v:a.getAsJsonArray("conditions"))require(words("protect kingsshield obstruct spikyshield banefulbunker silktrap burningbulwark matblock wideguard quickguard").contains(v.getAsString()),where,"Invalid partial shield");}
   if(op.equals("extraType")){require(a.has("values") && a.get("values").isJsonArray() && !a.getAsJsonArray("values").isEmpty(),where,"Invalid additional type roll");for(var v:a.getAsJsonArray("values"))require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(v.getAsString()),where,"Invalid additional type");if(a.has("layer"))require(words("field overlay").contains(a.get("layer").getAsString()),where,"Invalid type roll layer");for(String k:words("cycle excludePrimary"))if(a.has(k))require(a.getAsJsonPrimitive(k).isBoolean(),where,"Invalid type roll flag");}
   if(op.equals("randomWeather")){require(integer(a.get("duration"),1,20) && a.has("force") && a.getAsJsonPrimitive("force").isBoolean() && a.has("choices") && a.get("choices").isJsonArray() && a.getAsJsonArray("choices").size()>=2,where,"Invalid weather cycle");Set<String> seen=new HashSet<>();for(var v:a.getAsJsonArray("choices")){var r=v.getAsJsonObject();require(r.keySet().equals(words("id message")) && words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(r.get("id").getAsString()) && seen.add(r.get("id").getAsString()) && r.get("message").isJsonPrimitive() && r.getAsJsonPrimitive("message").isString(),where,"Invalid weather choice");}}
   if(op.equals("forEach")){require(words("foes allies others").contains(a.get("group").getAsString()),where,"Invalid action group");actions(a.getAsJsonArray("actions"),fields,where);}
   if(op.equals("forcedType"))require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(a.get("type").getAsString()),where,"Invalid forced type");
   if(op.equals("itemForm")){require(a.get("defaultSpecies").getAsString().matches("[a-z0-9]+") && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(a.get("defaultType").getAsString()) && !a.getAsJsonArray("variants").isEmpty(),where,"Invalid item form");for(var v:a.getAsJsonArray("variants")){var r=v.getAsJsonObject();require(r.keySet().equals(words("items species type")) && r.get("species").getAsString().matches("[a-z0-9]+") && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(r.get("type").getAsString()) && !r.getAsJsonArray("items").isEmpty(),where,"Invalid item form variant");for(var i:r.getAsJsonArray("items"))require(i.getAsString().matches("[a-z0-9]+"),where,"Invalid item form item");}}
   if(op.equals("randomType")){var values=a.getAsJsonArray("values");require(values!=null && !values.isEmpty() && (!a.has("force") || a.get("force").getAsJsonPrimitive().isBoolean()),where,"Invalid random type");for(var v:values)require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(v.getAsString()),where,"Invalid type ID");}
   if(op.equals("randomForm")){var values=a.getAsJsonArray("variants");require(values!=null && values.size()>1,where,"Missing random forms");for(var v:values){var r=v.getAsJsonObject();require(r.keySet().equals(words("species type")) && r.get("species").getAsString().matches("[a-z0-9]+") && words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy").contains(r.get("type").getAsString()),where,"Invalid random form");}}
   if(a.has("sourceAbility"))require(op.equals("boost") && a.get("sourceAbility").getAsString().equals("intimidate"),where,"Invalid boost source");
   if(a.has("silent"))require(op.equals("volatile") && a.get("silent").isJsonPrimitive() && a.getAsJsonPrimitive("silent").isBoolean(),where,"Invalid silent volatile");
   if(op.equals("secondaryChance"))require((!a.has("volatileStatus") || a.get("volatileStatus").getAsString().equals("flinch")) && (!a.has("chance") || integer(a.get("chance"),0,100)) && (!a.has("multiplier") || numeric(a.get("multiplier")) && a.get("multiplier").getAsDouble()>=0),where,"Invalid secondary chance");
   if(op.equals("addSecondary")){var r=a.getAsJsonObject("effect");require(a.get("duplicateKey").getAsString().equals("volatileStatus") && r.keySet().equals(words("chance volatileStatus")) && integer(r.get("chance"),1,100) && words("flinch confusion").contains(r.get("volatileStatus").getAsString()),where,"Invalid additional secondary");}
   if(op.equals("boost")){stats(a.getAsJsonObject("stats"),where);if(a.has("flavor")){require(a.get("flavor").isJsonPrimitive() && a.get("flavor").getAsString().matches("[a-z ]+"),where,"Invalid boost flavour");for(var e:a.getAsJsonObject("stats").entrySet())require(e.getValue().getAsInt()==1,where,"Invalid boost flavour");}}
   if(op.equals("randomStatus"))statusPool(a,fields,where);
   if(words("randomBoost randomStat").contains(op)){var s=a.getAsJsonArray("stats");require(s!=null && !s.isEmpty() && integer(a.get("amount"),-12,12) && a.get("amount").getAsInt()!=0,where,"Invalid random stat");for(var v:s)require(words("atk def spa spd spe accuracy evasion").contains(v.getAsString()),where,"Invalid random stat ID");}
   if(op.equals("transferStat")){var s=new JsonObject();s.add(a.get("stat").getAsString(),a.get("amount"));stats(s,where);}
   if(op.equals("bindFieldClock")){condition(a.get("durationCondition"),fields,where);condition(a.get("permanentCondition"),fields,where);}
   if(op.equals("changeField") && a.has("durationFromCondition"))require(words("gravity mudsport trickroom magicroom wonderroom").contains(a.get("durationFromCondition").getAsString()),where,"Invalid duration source");
   if(a.has("scaleField"))require(words("multiply cyclePower randomPower").contains(op) && a.getAsJsonPrimitive("scaleField").isBoolean(),where,"Invalid field scaling flag");
   if(op.equals("moveBehavior") && a.get("recipe").getAsString().equals("partialProtection")){require(a.has("conditions") && a.get("conditions").isJsonArray() && !a.getAsJsonArray("conditions").isEmpty() && numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1 && a.get("message").isJsonPrimitive() && a.getAsJsonPrimitive("message").isString(),where,"Invalid partial protection");for(var v:a.getAsJsonArray("conditions"))require(words("protect kingsshield obstruct spikyshield banefulbunker silktrap burningbulwark matblock wideguard quickguard").contains(v.getAsString()),where,"Invalid partial shield");}
   if(op.equals("extraType")){require(a.has("values") && a.get("values").isJsonArray() && !a.getAsJsonArray("values").isEmpty(),where,"Invalid additional type roll");for(var v:a.getAsJsonArray("values"))require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(v.getAsString()),where,"Invalid additional type");if(a.has("layer"))require(words("field overlay").contains(a.get("layer").getAsString()),where,"Invalid type roll layer");for(String k:words("cycle excludePrimary"))if(a.has(k))require(a.getAsJsonPrimitive(k).isBoolean(),where,"Invalid type roll flag");}
   if(op.equals("randomWeather")){require(integer(a.get("duration"),1,20) && a.has("force") && a.getAsJsonPrimitive("force").isBoolean() && a.has("choices") && a.get("choices").isJsonArray() && a.getAsJsonArray("choices").size()>=2,where,"Invalid weather cycle");Set<String> seen=new HashSet<>();for(var v:a.getAsJsonArray("choices")){var r=v.getAsJsonObject();require(r.keySet().equals(words("id message")) && words("sunnyday raindance sandstorm hail snow desolateland primordialsea deltastream shadowsky").contains(r.get("id").getAsString()) && seen.add(r.get("id").getAsString()) && r.get("message").isJsonPrimitive() && r.getAsJsonPrimitive("message").isString(),where,"Invalid weather choice");}}
   if(op.equals("forEach")){if(a.has("condition"))condition(a.get("condition"),fields,where);require((!a.has("anchor") || a.get("anchor").getAsString().equals("holder")) && (!a.has("order") || a.get("order").getAsString().equals("speed")) && (!a.has("message") || a.get("message").isJsonPrimitive() && a.getAsJsonPrimitive("message").isString()),where,"Invalid iteration options");}
   if(op.equals("heal") && a.has("messageFrom"))require(a.get("messageFrom").getAsString().equals("user"),where,"Invalid healing message actor");
   if(op.equals("fieldMove"))require(a.has("move") && a.get("move").isJsonPrimitive() && a.getAsJsonPrimitive("move").isString() && a.get("move").getAsString().matches("[a-z0-9]+"),where,"Invalid field move");
   if(op.equals("heal") && a.has("failureMessage"))require(a.get("failureMessage").isJsonPrimitive() && a.getAsJsonPrimitive("failureMessage").isString(),where,"Invalid healing failure message");
   if(op.equals("castling")){stats(a.getAsJsonObject("userStats"),where);stats(a.getAsJsonObject("partnerStats"),where);require(a.has("message") && a.get("message").isJsonPrimitive() && a.getAsJsonPrimitive("message").isString(),where,"Missing castling message");}
   if(op.equals("changeField")){require(!a.has("duration") || integer(a.get("duration"),0,20),where,"Invalid temporary duration");require(!a.has("force") || a.get("force").getAsJsonPrimitive().isBoolean(),where,"Invalid force flag");require(!a.has("boundCondition") || a.get("boundCondition").getAsString().matches("[a-z0-9]+"),where,"Invalid clock condition");}
   if(words("multiply add cap").contains(op))require(numeric(a.get("value")),where,"Invalid numeric action");
   if(op.equals("volatileDuration"))require(a.has("id") && a.get("id").getAsString().matches("[a-z0-9]+") && integer(a.get("amount"),-20,20) && a.get("amount").getAsInt()!=0 && integer(a.get("minimum"),1,20),where,"Invalid volatile duration change");
   if(op.equals("trap"))require(!a.has("force") || a.get("force").getAsJsonPrimitive().isBoolean(),where,"Invalid trap policy");
   if(op.equals("clearHazards"))require(a.has("message") && a.get("message").isJsonPrimitive() && !a.get("message").getAsString().isEmpty(),where,"Invalid hazard clearing message");
   if(words("heal damage typedDamage residualDamage wish adjustWish setHPFraction").contains(op))require(numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1,where,"Invalid HP fraction");
   if(words("changeField weatherTemporary").contains(op))require(fields.has(a.get("field").getAsString()),where,"Missing action field");
   if(op.equals("moveProperty")){require(PATHS.contains(a.get("path").getAsString()),where,"Invalid move property path");if(words("overrideOffensiveStat overrideDefensiveStat").contains(a.get("path").getAsString()))require(words("atk def spa spd spe").contains(a.get("value").getAsString()),where,"Invalid stat override");if(a.get("path").getAsString().equals("secondaries.0.self"))require(a.has("value") && a.get("value").isJsonNull(),where,"Invalid secondary self override");if(a.get("path").getAsString().equals("ignoreImmunity"))require(a.get("value").isJsonObject() && a.getAsJsonObject("value").size()==1 && a.getAsJsonObject("value").has("Ground") && a.getAsJsonObject("value").get("Ground").isJsonPrimitive() && a.getAsJsonObject("value").get("Ground").getAsJsonPrimitive().isBoolean() && a.getAsJsonObject("value").get("Ground").getAsBoolean(),where,"Invalid immunity override");if(a.get("path").getAsString().equals("drain"))require(a.get("value").isJsonArray() && a.getAsJsonArray("value").size()==2 && integer(a.getAsJsonArray("value").get(0),1,100) && integer(a.getAsJsonArray("value").get(1),1,100) && a.getAsJsonArray("value").get(0).getAsInt()<=a.getAsJsonArray("value").get(1).getAsInt(),where,"Invalid drain share");if(a.get("path").getAsString().equals("magnitude"))require(integer(a.get("value"),4,10),where,"Invalid magnitude");if(a.get("path").getAsString().equals("maxHPRecoil"))require(numeric(a.get("value")) && a.get("value").getAsDouble()>0 && a.get("value").getAsDouble()<=1,where,"Invalid max-HP recoil");}
   if(op.equals("sideCondition")){
    require(words("mist safeguard luckychant reflect lightscreen auroraveil tailwind spikes toxicspikes stealthrock stickyweb").contains(a.get("id").getAsString()),where,"Invalid side condition");
    if(a.has("duration"))require(numeric(a.get("duration")) && a.get("duration").getAsDouble()==a.get("duration").getAsInt() && a.get("duration").getAsInt()>0 && a.get("duration").getAsInt()<=20,where,"Invalid side duration");
   }
   if(op.equals("createField")){
    if(a.has("blockEverstone"))require(a.get("blockEverstone").getAsJsonPrimitive().isBoolean(),where,"Invalid Everstone policy");
    require(fields.has(a.get("field").getAsString()),where,"Invalid field creation target");
    for(String key:List.of("duration","extendedBy"))require(numeric(a.get(key)) && a.get(key).getAsDouble()==a.get(key).getAsInt() && a.get(key).getAsInt()>=(key.equals("duration")?1:0) && a.get(key).getAsInt()<=20,where,"Invalid field creation clock");
   }
   if(op.equals("criticalStage"))require(words("focusenergy dragoncheer").contains(a.get("id").getAsString()) && numeric(a.get("stage")) && a.get("stage").getAsInt()>=1 && a.get("stage").getAsInt()<=3,where,"Invalid critical stage");
   if(op.equals("weightDelta"))require(numeric(a.get("baseMultiplier")) && a.get("baseMultiplier").getAsDouble()>0,where,"Invalid weight increment");
   if(op.equals("removeCallbacks"))for(var c:a.getAsJsonArray("callbacks"))require(words("onPrepareHit onTry onTryHit onModifyMove onHit basePowerCallback").contains(c.getAsString()),where,"Invalid callback removal");
   if(op.equals("pairField")){
    require(words("pledge conversion").contains(a.get("memory").getAsString()),where,"Invalid pair memory");
    require(numeric(a.get("duration")) && a.get("duration").getAsInt()>0 && a.get("duration").getAsInt()<=20 && numeric(a.get("extendedBy")) && a.get("extendedBy").getAsInt()>=0,where,"Invalid pair duration");
    if(a.has("disallowPermanentField"))require(fields.has(a.get("disallowPermanentField").getAsString()),where,"Unknown permanent restriction");
    for(var row:a.getAsJsonArray("pairs"))require(fields.has(row.getAsJsonObject().get("field").getAsString()),where,"Unknown paired field");
   }
   if(a.has("removeCallback"))require(words("onHit onTry onBasePower basePowerCallback").contains(a.get("removeCallback").getAsString()),where,"Invalid callback removal");
   if(a.has("silentCommands")){require(!a.getAsJsonArray("silentCommands").isEmpty(),where,"Empty silent command policy");for(var v:a.getAsJsonArray("silentCommands"))require(words("swap -start -status").contains(v.getAsString()),where,"Invalid silent command policy");}
   if(op.equals("moveBehavior") && a.get("recipe").getAsString().equals("smartCategory")){
    require(words("offense difference").contains(a.get("comparison").getAsString()) && a.get("contactByCategory").getAsJsonPrimitive().isBoolean(),where,"Invalid smart category");
    for(String key:List.of("physicalMultipliers","specialMultipliers","defenseMultipliers","specialDefenseMultipliers")){require(a.has(key) && a.get(key).isJsonArray(),where,"Missing category multipliers");for(var entryRow:a.getAsJsonArray(key)){var row=entryRow.getAsJsonObject();require(row.keySet().equals(words("condition factor")) && numeric(row.get("factor")) && row.get("factor").getAsDouble()>0 && row.get("factor").getAsDouble()<=4,where,"Invalid category multiplier");condition(row.get("condition"),fields,where);}}
   }
   if(op.equals("moveBehavior")){
    String recipe=a.get("recipe").getAsString();require(words("partialProtection smartCategory cureAndBoost setTypes appendHitActions payHP fixedDamage targetWeightPower boostOnly shareHP deductPP arenaRoar firstTypeBonus refreshVolatileBeforeHit reapplyStatusHeal replaceHitActions otherActiveHitActions randomStatusSecondary boostStagePower allActiveHitActions weightRatioPower purify swallow randomPowerCallback forceBasePower appendSecondaryActions alliesHitActions beforeCalledMoveActions randomMovePool strengthSap targetHealing concertRoar dualBoost gatedStatChanges").contains(recipe),where,"Unknown move recipe");
    if(recipe.equals("refreshVolatileBeforeHit"))require(a.has("id") && a.get("id").getAsString().matches("[a-z0-9]+"),where,"Invalid refreshed volatile");
    if(recipe.equals("reapplyStatusHeal"))require(a.has("status") && words("slp brn par psn tox frz").contains(a.get("status").getAsString()) && numeric(a.get("duration")) && a.get("duration").getAsDouble()==a.get("duration").getAsInt() && a.get("duration").getAsInt()>0 && a.get("duration").getAsInt()<=20 && numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1,where,"Invalid status refresh/heal");
    if(words("appendHitActions appendSecondaryActions replaceHitActions otherActiveHitActions allActiveHitActions alliesHitActions beforeCalledMoveActions targetHealing").contains(recipe))actions(a.getAsJsonArray("actions"),fields,where+"/hit");
    if(words("allActiveHitActions alliesHitActions").contains(recipe))condition(a.get("condition"),fields,where);
    if(recipe.equals("randomStatusSecondary"))statusPool(a,fields,where);
    if(words("boostStagePower forceBasePower").contains(recipe))require(integer(a.get("base"),1,1000),where,"Invalid fixed base power");
    if(recipe.equals("weightRatioPower"))require(numeric(a.get("multiplier")) && a.get("multiplier").getAsDouble()>0 && a.get("multiplier").getAsDouble()<=10,where,"Invalid weight ratio");
    if(recipe.equals("randomPowerCallback")){probability(a,where);require(integer(a.get("base"),1,1000) && integer(a.get("boosted"),1,1000),where,"Invalid chance power");}
    if(words("purify strengthSap concertRoar").contains(recipe))stats(a.getAsJsonObject("stats"),where);
    if(words("purify targetHealing").contains(recipe))for(String key:List.of("fraction","userFraction")){if(key.equals("userFraction") && !a.has(key))continue;require(numeric(a.get(key)) && a.get(key).getAsDouble()>0 && a.get(key).getAsDouble()<=1,where,"Invalid healing fraction");}
    if(recipe.equals("swallow")){var fs=a.getAsJsonArray("fractions");require(fs!=null && fs.size()==3 && integer(a.get("cureAt"),1,3),where,"Invalid stockpile healing");for(var v:fs)require(numeric(v) && v.getAsDouble()>0 && v.getAsDouble()<=1,where,"Invalid stockpile fraction");}
    if(recipe.equals("gatedStatChanges")){stats(a.getAsJsonObject("stats"),where);stats(a.getAsJsonObject("gateStats"),where);require(words("user target").contains(a.get("gateWho").getAsString()) && a.get("selfSwitch").getAsJsonPrimitive().isBoolean() && a.get("failureMessage").getAsJsonPrimitive().isString(),where,"Invalid gated stat change");}
    if(recipe.equals("dualBoost")){stats(a.getAsJsonObject("targetStats"),where);stats(a.getAsJsonObject("userStats"),where);}
    if(recipe.equals("randomMovePool")){require(integer(a.get("minimumPower"),1,1000) && a.has("choices") && a.get("choices").isJsonArray() && !a.getAsJsonArray("choices").isEmpty(),where,"Invalid random move pool");var seen=new HashSet<String>();for(var mid:a.getAsJsonArray("choices"))require(mid.isJsonPrimitive() && mid.getAsString().matches("[a-z0-9]+") && seen.add(mid.getAsString()),where,"Invalid or duplicate calling move");}
    if(recipe.equals("beforeCalledMoveActions"))require(a.has("callback") && a.get("callback").getAsString().equals("onTryHit"),where,"Invalid caller callback");
    if(recipe.equals("appendHitActions"))require(!a.has("callback") || words("onHit onHitSide onAfterHit onHitField").contains(a.get("callback").getAsString()),where,"Invalid hit action callback");
    if(recipe.equals("deductPP"))require(numeric(a.get("amount")) && a.get("amount").getAsDouble()==a.get("amount").getAsInt() && a.get("amount").getAsInt()>0 && a.get("amount").getAsInt()<=64,where,"Invalid PP deduction");
    if(recipe.equals("firstTypeBonus"))require(words("Normal Fire Water Electric Grass Ice Fighting Poison Ground Flying Psychic Bug Rock Ghost Dragon Dark Steel Fairy Shadow ???").contains(a.get("type").getAsString()) && numeric(a.get("repeat")) && a.get("repeat").getAsDouble()==a.get("repeat").getAsInt() && a.get("repeat").getAsInt()>=1 && a.get("repeat").getAsInt()<=3 && a.get("positiveOnly").isJsonPrimitive() && a.get("positiveOnly").getAsJsonPrimitive().isBoolean(),where,"Invalid first-type bonus");
    if(recipe.equals("payHP")){require(numeric(a.get("fraction")) && a.get("fraction").getAsDouble()>0 && a.get("fraction").getAsDouble()<=1,where,"Invalid HP cost");require(!a.has("callback") || words("onHit onAfterMove").contains(a.get("callback").getAsString()),where,"Invalid cost callback");
     require(!a.has("requireHit") || a.get("requireHit").isJsonPrimitive() && a.get("requireHit").getAsJsonPrimitive().isBoolean() && a.get("requireHit").getAsBoolean() && a.has("callback") && a.get("callback").getAsString().equals("onAfterMove"),where,"Invalid cost hit requirement");}
    if(recipe.equals("fixedDamage")){
     require(words("level targetHP targetMaxHP constant").contains(a.get("basis").getAsString()) && numeric(a.get("factor")) && a.get("factor").getAsDouble()>0 && a.get("factor").getAsDouble()<=2,where,"Invalid fixed damage");
     require(a.get("basis").getAsString().equals("constant")==a.has("amount") && (!a.has("amount") || integer(a.get("amount"),1,9999)),where,"Invalid fixed damage amount");
     if(a.has("randomRange")){var r=a.getAsJsonObject("randomRange");require(numeric(r.get("minimum")) && numeric(r.get("maximum")) && r.get("minimum").getAsInt()>0 && r.get("maximum").getAsInt()>=r.get("minimum").getAsInt(),where,"Invalid random damage range");}
    }
   }
   if(a.has("maximize"))condition(a.get("maximize"),fields,where);
   if(a.has("modifiers"))for(var m:a.getAsJsonArray("modifiers"))condition(m.getAsJsonObject().get("condition"),fields,where);
  }
 }
}
